package com.asteroid;

import com.asteroid.dao.T_Compare;
import com.asteroid.dao.T_CompareField;
import com.asteroid.entity.Bean_Two;
import com.wangtiantian.dao.T_Config_File;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.FileOutputStream;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

import static com.asteroid.Main.method_获取excel表头;

public class MainRunTest {
    public static void main(String[] args) {
        T_Compare compare = new T_Compare(2, 1, 3);
        T_Compare insertCompare = new T_Compare(2, 1, 3);
        ArrayList<Object> dataList = new ArrayList<>();
//        ArrayList<Object> qczjDataList = compare.get_除匹配上的汽车之家数据();
//        for (Object autoData : qczjDataList) {
//            Bean_Two autoBean = new Bean_Two();
//            autoBean.set_C_汽车之家的版本Id(((Bean_Two) autoData).get_C_汽车之家的版本Id());
//            System.out.println(((Bean_Two) autoData).get_C_汽车之家的版本Id());
//            autoBean.set_C_易车的版本Id(((Bean_Two) autoData).get_C_易车的版本Id());
////            autoBean.set_C_汽车之家版本Id_易车版本Id(((Bean_Two) autoData).get_C_汽车之家版本Id_易车版本Id());
//
//            autoBean.set_C_汽车之家_C_座椅配置__座椅材质(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__座椅材质());
//            autoBean.set_C_汽车之家_C_座椅配置__座椅布局(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__座椅布局());
//            autoBean.set_C_汽车之家_C_座椅配置__主座椅调节方式(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__主座椅调节方式());
//            autoBean.set_C_汽车之家_C_座椅配置__主_副驾驶座电动调节(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__主_副驾驶座电动调节());
//            autoBean.set_C_汽车之家_C_座椅配置__运动风格座椅(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__运动风格座椅());
//            autoBean.set_C_汽车之家_C_座椅配置__零重力座椅(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__零重力座椅());
//            autoBean.set_C_汽车之家_C_座椅配置__加热_制冷杯架(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__加热_制冷杯架());
//            autoBean.set_C_汽车之家_C_座椅配置__后排座椅放倒形式(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__后排座椅放倒形式());
//            autoBean.set_C_汽车之家_C_座椅配置__后排座椅电动放倒(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__后排座椅电动放倒());
//            autoBean.set_C_汽车之家_C_座椅配置__后排小桌板(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__后排小桌板());
//            autoBean.set_C_汽车之家_C_座椅配置__后排杯架(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__后排杯架());
//            autoBean.set_C_汽车之家_C_座椅配置__副座椅调节方式(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__副座椅调节方式());
//            autoBean.set_C_汽车之家_C_座椅配置__福祉座椅(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__福祉座椅());
//            autoBean.set_C_汽车之家_C_座椅配置__第三排座椅调节(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__第三排座椅调节());
//            autoBean.set_C_汽车之家_C_座椅配置__第三排座椅功能(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__第三排座椅功能());
//            autoBean.set_C_汽车之家_C_座椅配置__第三排座椅电动调节(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__第三排座椅电动调节());
//            autoBean.set_C_汽车之家_C_座椅配置__第二排座椅调节(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__第二排座椅调节());
//            autoBean.set_C_汽车之家_C_座椅配置__第二排座椅功能(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__第二排座椅功能());
//            autoBean.set_C_汽车之家_C_座椅配置__第二排座椅电动调节(((Bean_Two) autoData).get_C_汽车之家_C_座椅配置__第二排座椅电动调节());
//            autoBean.set_C_汽车之家_C_主动安全__主动刹车_主动安全系统(((Bean_Two) autoData).get_C_汽车之家_C_主动安全__主动刹车_主动安全系统());
//            autoBean.set_C_汽车之家_C_主动安全__制动力分配_EBD_CBC等(((Bean_Two) autoData).get_C_汽车之家_C_主动安全__制动力分配_EBD_CBC等());
//            autoBean.set_C_汽车之家_C_主动安全__胎压监测功能(((Bean_Two) autoData).get_C_汽车之家_C_主动安全__胎压监测功能());
//            autoBean.set_C_汽车之家_C_主动安全__哨兵模式_千里眼(((Bean_Two) autoData).get_C_汽车之家_C_主动安全__哨兵模式_千里眼());
//            autoBean.set_C_汽车之家_C_主动安全__前方碰撞预警(((Bean_Two) autoData).get_C_汽车之家_C_主动安全__前方碰撞预警());
//            autoBean.set_C_汽车之家_C_主动安全__牵引力控制_ASR_TCS_TRC等(((Bean_Two) autoData).get_C_汽车之家_C_主动安全__牵引力控制_ASR_TCS_TRC等());
//            autoBean.set_C_汽车之家_C_主动安全__疲劳驾驶提示(((Bean_Two) autoData).get_C_汽车之家_C_主动安全__疲劳驾驶提示());
//            autoBean.set_C_汽车之家_C_主动安全__内置行车记录仪(((Bean_Two) autoData).get_C_汽车之家_C_主动安全__内置行车记录仪());
//            autoBean.set_C_汽车之家_C_主动安全__后方碰撞预警(((Bean_Two) autoData).get_C_汽车之家_C_主动安全__后方碰撞预警());
//            autoBean.set_C_汽车之家_C_主动安全__防侧翻系统(((Bean_Two) autoData).get_C_汽车之家_C_主动安全__防侧翻系统());
//            autoBean.set_C_汽车之家_C_主动安全__低速行车警告(((Bean_Two) autoData).get_C_汽车之家_C_主动安全__低速行车警告());
//            autoBean.set_C_汽车之家_C_主动安全__道路救援呼叫(((Bean_Two) autoData).get_C_汽车之家_C_主动安全__道路救援呼叫());
//            autoBean.set_C_汽车之家_C_主动安全__车身稳定控制_ESC_ESP_DSC等(((Bean_Two) autoData).get_C_汽车之家_C_主动安全__车身稳定控制_ESC_ESP_DSC等());
//            autoBean.set_C_汽车之家_C_主动安全__刹车辅助_EBA_BAS_BA等(((Bean_Two) autoData).get_C_汽车之家_C_主动安全__刹车辅助_EBA_BAS_BA等());
//            autoBean.set_C_汽车之家_C_主动安全__安全带未系提醒(((Bean_Two) autoData).get_C_汽车之家_C_主动安全__安全带未系提醒());
//            autoBean.set_C_汽车之家_C_主动安全__ISOFIX儿童座椅接口(((Bean_Two) autoData).get_C_汽车之家_C_主动安全__ISOFIX儿童座椅接口());
//            autoBean.set_C_汽车之家_C_主动安全__ABS防抱死(((Bean_Two) autoData).get_C_汽车之家_C_主动安全__ABS防抱死());
//            autoBean.set_C_汽车之家_C_智能化配置__主动降噪(((Bean_Two) autoData).get_C_汽车之家_C_智能化配置__主动降噪());
//            autoBean.set_C_汽车之家_C_智能化配置__模拟声浪(((Bean_Two) autoData).get_C_汽车之家_C_智能化配置__模拟声浪());
//            autoBean.set_C_汽车之家_C_智能化配置__车内生物监测系统(((Bean_Two) autoData).get_C_汽车之家_C_智能化配置__车内生物监测系统());
//            autoBean.set_C_汽车之家_C_智能化配置__V2X通讯(((Bean_Two) autoData).get_C_汽车之家_C_智能化配置__V2X通讯());
//            autoBean.set_C_汽车之家_C_智能化配置__OTA升级(((Bean_Two) autoData).get_C_汽车之家_C_智能化配置__OTA升级());
//            autoBean.set_C_汽车之家_C_音响_车内灯光__主动式环境氛围灯(((Bean_Two) autoData).get_C_汽车之家_C_音响_车内灯光__主动式环境氛围灯());
//            autoBean.set_C_汽车之家_C_音响_车内灯光__扬声器数量(((Bean_Two) autoData).get_C_汽车之家_C_音响_车内灯光__扬声器数量());
//            autoBean.set_C_汽车之家_C_音响_车内灯光__车内环境氛围灯(((Bean_Two) autoData).get_C_汽车之家_C_音响_车内灯光__车内环境氛围灯());
//            autoBean.set_C_汽车之家_C_外观_防盗__自动开合车门(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__自动开合车门());
//            autoBean.set_C_汽车之家_C_外观_防盗__主动闭合式进气格栅(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__主动闭合式进气格栅());
//            autoBean.set_C_汽车之家_C_外观_防盗__整车无线充电(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__整车无线充电());
//            autoBean.set_C_汽车之家_C_外观_防盗__隐藏电动门把手(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__隐藏电动门把手());
//            autoBean.set_C_汽车之家_C_外观_防盗__钥匙类型(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__钥匙类型());
//            autoBean.set_C_汽车之家_C_外观_防盗__无钥匙启动系统(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__无钥匙启动系统());
//            autoBean.set_C_汽车之家_C_外观_防盗__无钥匙进入功能(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__无钥匙进入功能());
//            autoBean.set_C_汽车之家_C_外观_防盗__无框设计车门(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__无框设计车门());
//            autoBean.set_C_汽车之家_C_外观_防盗__尾门玻璃独立开启(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__尾门玻璃独立开启());
//            autoBean.set_C_汽车之家_C_外观_防盗__外观套件(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__外观套件());
//            autoBean.set_C_汽车之家_C_外观_防盗__轮圈材质(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__轮圈材质());
//            autoBean.set_C_汽车之家_C_外观_防盗__感应后备厢(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__感应后备厢());
//            autoBean.set_C_汽车之家_C_外观_防盗__对外放电(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__对外放电());
//            autoBean.set_C_汽车之家_C_外观_防盗__电动吸合车门(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__电动吸合车门());
//            autoBean.set_C_汽车之家_C_外观_防盗__电动扰流板(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__电动扰流板());
//            autoBean.set_C_汽车之家_C_外观_防盗__电动后备厢位置记忆(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__电动后备厢位置记忆());
//            autoBean.set_C_汽车之家_C_外观_防盗__电动后备厢(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__电动后备厢());
//            autoBean.set_C_汽车之家_C_外观_防盗__车顶行李架(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__车顶行李架());
//            autoBean.set_C_汽车之家_C_外观_防盗__车侧脚踏板(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__车侧脚踏板());
//            autoBean.set_C_汽车之家_C_外观_防盗__侧滑门形式(((Bean_Two) autoData).get_C_汽车之家_C_外观_防盗__侧滑门形式());
//            autoBean.set_C_汽车之家_C_天窗_玻璃__天窗类型(((Bean_Two) autoData).get_C_汽车之家_C_天窗_玻璃__天窗类型());
//            autoBean.set_C_汽车之家_C_天窗_玻璃__可加热喷水嘴(((Bean_Two) autoData).get_C_汽车之家_C_天窗_玻璃__可加热喷水嘴());
//            autoBean.set_C_汽车之家_C_天窗_玻璃__后雨刷(((Bean_Two) autoData).get_C_汽车之家_C_天窗_玻璃__后雨刷());
//            autoBean.set_C_汽车之家_C_天窗_玻璃__后排侧隐私玻璃(((Bean_Two) autoData).get_C_汽车之家_C_天窗_玻璃__后排侧隐私玻璃());
//            autoBean.set_C_汽车之家_C_天窗_玻璃__后排侧窗遮阳帘(((Bean_Two) autoData).get_C_汽车之家_C_天窗_玻璃__后排侧窗遮阳帘());
//            autoBean.set_C_汽车之家_C_天窗_玻璃__后风挡遮阳帘(((Bean_Two) autoData).get_C_汽车之家_C_天窗_玻璃__后风挡遮阳帘());
//            autoBean.set_C_汽车之家_C_天窗_玻璃__光感天幕(((Bean_Two) autoData).get_C_汽车之家_C_天窗_玻璃__光感天幕());
//            autoBean.set_C_汽车之家_C_天窗_玻璃__感应雨刷功能(((Bean_Two) autoData).get_C_汽车之家_C_天窗_玻璃__感应雨刷功能());
//            autoBean.set_C_汽车之家_C_天窗_玻璃__车内化妆镜(((Bean_Two) autoData).get_C_汽车之家_C_天窗_玻璃__车内化妆镜());
//            autoBean.set_C_汽车之家_C_天窗_玻璃__车窗一键升降功能(((Bean_Two) autoData).get_C_汽车之家_C_天窗_玻璃__车窗一键升降功能());
//            autoBean.set_C_汽车之家_C_天窗_玻璃__车窗防夹手功能(((Bean_Two) autoData).get_C_汽车之家_C_天窗_玻璃__车窗防夹手功能());
//            autoBean.set_C_汽车之家_C_天窗_玻璃__侧窗多层隔音玻璃(((Bean_Two) autoData).get_C_汽车之家_C_天窗_玻璃__侧窗多层隔音玻璃());
//            autoBean.set_C_汽车之家_C_四驱_越野__限滑差速器_差速锁(((Bean_Two) autoData).get_C_汽车之家_C_四驱_越野__限滑差速器_差速锁());
//            autoBean.set_C_汽车之家_C_四驱_越野__拖挂钩(((Bean_Two) autoData).get_C_汽车之家_C_四驱_越野__拖挂钩());
//            autoBean.set_C_汽车之家_C_四驱_越野__拖车取电口(((Bean_Two) autoData).get_C_汽车之家_C_四驱_越野__拖车取电口());
//            autoBean.set_C_汽车之家_C_四驱_越野__坦克转弯(((Bean_Two) autoData).get_C_汽车之家_C_四驱_越野__坦克转弯());
//            autoBean.set_C_汽车之家_C_四驱_越野__涉水感应系统(((Bean_Two) autoData).get_C_汽车之家_C_四驱_越野__涉水感应系统());
//            autoBean.set_C_汽车之家_C_四驱_越野__蠕行模式(((Bean_Two) autoData).get_C_汽车之家_C_四驱_越野__蠕行模式());
//            autoBean.set_C_汽车之家_C_四驱_越野__低速四驱(((Bean_Two) autoData).get_C_汽车之家_C_四驱_越野__低速四驱());
//            autoBean.set_C_汽车之家_C_屏幕_系统__中控下屏幕像素密度(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__中控下屏幕像素密度());
//            autoBean.set_C_汽车之家_C_屏幕_系统__中控下屏幕类型(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__中控下屏幕类型());
//            autoBean.set_C_汽车之家_C_屏幕_系统__中控下屏幕分辨率(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__中控下屏幕分辨率());
//            autoBean.set_C_汽车之家_C_屏幕_系统__中控下屏幕尺寸(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__中控下屏幕尺寸());
//            autoBean.set_C_汽车之家_C_屏幕_系统__中控屏幕像素密度(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__中控屏幕像素密度());
//            autoBean.set_C_汽车之家_C_屏幕_系统__中控屏幕类型(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__中控屏幕类型());
//            autoBean.set_C_汽车之家_C_屏幕_系统__中控屏幕分辨率(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__中控屏幕分辨率());
//            autoBean.set_C_汽车之家_C_屏幕_系统__中控屏幕尺寸(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__中控屏幕尺寸());
//            autoBean.set_C_汽车之家_C_屏幕_系统__中控彩色屏幕(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__中控彩色屏幕());
//            autoBean.set_C_汽车之家_C_屏幕_系统__语音助手唤醒词(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__语音助手唤醒词());
//            autoBean.set_C_汽车之家_C_屏幕_系统__语音识别控制系统(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__语音识别控制系统());
//            autoBean.set_C_汽车之家_C_屏幕_系统__语音免唤醒词(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__语音免唤醒词());
//            autoBean.set_C_汽车之家_C_屏幕_系统__语音连续识别(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__语音连续识别());
//            autoBean.set_C_汽车之家_C_屏幕_系统__语音分区域唤醒识别(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__语音分区域唤醒识别());
//            autoBean.set_C_汽车之家_C_屏幕_系统__应用商店(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__应用商店());
//            autoBean.set_C_汽车之家_C_屏幕_系统__手势控制(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__手势控制());
//            autoBean.set_C_汽车之家_C_屏幕_系统__手机互联_映射(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__手机互联_映射());
//            autoBean.set_C_汽车之家_C_屏幕_系统__面部识别(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__面部识别());
//            autoBean.set_C_汽车之家_C_屏幕_系统__蓝牙_车载电话(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__蓝牙_车载电话());
//            autoBean.set_C_汽车之家_C_屏幕_系统__后排液晶屏幕像素密度(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__后排液晶屏幕像素密度());
//            autoBean.set_C_汽车之家_C_屏幕_系统__后排液晶屏幕分辨率(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__后排液晶屏幕分辨率());
//            autoBean.set_C_汽车之家_C_屏幕_系统__后排液晶屏幕尺寸(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__后排液晶屏幕尺寸());
//            autoBean.set_C_汽车之家_C_屏幕_系统__后排液晶屏幕(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__后排液晶屏幕());
//            autoBean.set_C_汽车之家_C_屏幕_系统__后排控制多媒体(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__后排控制多媒体());
//            autoBean.set_C_汽车之家_C_屏幕_系统__后排多媒体屏幕数量(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__后排多媒体屏幕数量());
//            autoBean.set_C_汽车之家_C_屏幕_系统__副驾娱乐屏尺寸(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__副驾娱乐屏尺寸());
//            autoBean.set_C_汽车之家_C_屏幕_系统__副驾屏幕像素密度(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__副驾屏幕像素密度());
//            autoBean.set_C_汽车之家_C_屏幕_系统__副驾屏幕类型(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__副驾屏幕类型());
//            autoBean.set_C_汽车之家_C_屏幕_系统__副驾屏幕分辨率(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__副驾屏幕分辨率());
//            autoBean.set_C_汽车之家_C_屏幕_系统__多指飞屏操控(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__多指飞屏操控());
//            autoBean.set_C_汽车之家_C_屏幕_系统__车载CD_DVD(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__车载CD_DVD());
//            autoBean.set_C_汽车之家_C_屏幕_系统__车机智能芯片(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__车机智能芯片());
//            autoBean.set_C_汽车之家_C_屏幕_系统__车机系统内存_GB(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__车机系统内存_GB());
//            autoBean.set_C_汽车之家_C_屏幕_系统__车机系统存储_GB(((Bean_Two) autoData).get_C_汽车之家_C_屏幕_系统__车机系统存储_GB());
//            autoBean.set_C_汽车之家_C_空调_冰箱__热泵空调(((Bean_Two) autoData).get_C_汽车之家_C_空调_冰箱__热泵空调());
//            autoBean.set_C_汽车之家_C_空调_冰箱__空气质量监测(((Bean_Two) autoData).get_C_汽车之家_C_空调_冰箱__空气质量监测());
//            autoBean.set_C_汽车之家_C_空调_冰箱__负离子发生器(((Bean_Two) autoData).get_C_汽车之家_C_空调_冰箱__负离子发生器());
//            autoBean.set_C_汽车之家_C_空调_冰箱__车载空气净化器(((Bean_Two) autoData).get_C_汽车之家_C_空调_冰箱__车载空气净化器());
//            autoBean.set_C_汽车之家_C_空调_冰箱__车载冰箱(((Bean_Two) autoData).get_C_汽车之家_C_空调_冰箱__车载冰箱());
//            autoBean.set_C_汽车之家_C_空调_冰箱__车内香氛装置(((Bean_Two) autoData).get_C_汽车之家_C_空调_冰箱__车内香氛装置());
//            autoBean.set_C_汽车之家_C_空调_冰箱__车内PM2_5过滤装置(((Bean_Two) autoData).get_C_汽车之家_C_空调_冰箱__车内PM2_5过滤装置());
//            autoBean.set_C_汽车之家_C_驾驶硬件__前方感知摄像头像素(((Bean_Two) autoData).get_C_汽车之家_C_驾驶硬件__前方感知摄像头像素());
//            autoBean.set_C_汽车之家_C_驾驶硬件__前方感知摄像头(((Bean_Two) autoData).get_C_汽车之家_C_驾驶硬件__前方感知摄像头());
//            autoBean.set_C_汽车之家_C_驾驶硬件__前_后驻车雷达(((Bean_Two) autoData).get_C_汽车之家_C_驾驶硬件__前_后驻车雷达());
//            autoBean.set_C_汽车之家_C_驾驶硬件__驾驶辅助影像(((Bean_Two) autoData).get_C_汽车之家_C_驾驶硬件__驾驶辅助影像());
//            autoBean.set_C_汽车之家_C_驾驶硬件__激光雷达型号(((Bean_Two) autoData).get_C_汽车之家_C_驾驶硬件__激光雷达型号());
//            autoBean.set_C_汽车之家_C_驾驶硬件__激光雷达线数(((Bean_Two) autoData).get_C_汽车之家_C_驾驶硬件__激光雷达线数());
//            autoBean.set_C_汽车之家_C_驾驶硬件__激光雷达数量(((Bean_Two) autoData).get_C_汽车之家_C_驾驶硬件__激光雷达数量());
//            autoBean.set_C_汽车之家_C_驾驶硬件__激光雷达品牌(((Bean_Two) autoData).get_C_汽车之家_C_驾驶硬件__激光雷达品牌());
//            autoBean.set_C_汽车之家_C_驾驶硬件__激光雷达点云数量(((Bean_Two) autoData).get_C_汽车之家_C_驾驶硬件__激光雷达点云数量());
//            autoBean.set_C_汽车之家_C_驾驶硬件__激光雷达10_反射率探测距离(((Bean_Two) autoData).get_C_汽车之家_C_驾驶硬件__激光雷达10_反射率探测距离());
//            autoBean.set_C_汽车之家_C_驾驶硬件__环视摄像头像素(((Bean_Two) autoData).get_C_汽车之家_C_驾驶硬件__环视摄像头像素());
//            autoBean.set_C_汽车之家_C_驾驶硬件__环境感知摄像头像素(((Bean_Two) autoData).get_C_汽车之家_C_驾驶硬件__环境感知摄像头像素());
//            autoBean.set_C_汽车之家_C_驾驶硬件__毫米波雷达数量(((Bean_Two) autoData).get_C_汽车之家_C_驾驶硬件__毫米波雷达数量());
//            autoBean.set_C_汽车之家_C_驾驶硬件__辅助驾驶芯片(((Bean_Two) autoData).get_C_汽车之家_C_驾驶硬件__辅助驾驶芯片());
//            autoBean.set_C_汽车之家_C_驾驶硬件__车内摄像头数量(((Bean_Two) autoData).get_C_汽车之家_C_驾驶硬件__车内摄像头数量());
//            autoBean.set_C_汽车之家_C_驾驶硬件__超声波雷达数量(((Bean_Two) autoData).get_C_汽车之家_C_驾驶硬件__超声波雷达数量());
//            autoBean.set_C_汽车之家_C_驾驶功能__自动泊车入位(((Bean_Two) autoData).get_C_汽车之家_C_驾驶功能__自动泊车入位());
//            autoBean.set_C_汽车之家_C_驾驶功能__自动变道辅助(((Bean_Two) autoData).get_C_汽车之家_C_驾驶功能__自动变道辅助());
//            autoBean.set_C_汽车之家_C_驾驶功能__匝道自动驶出_入(((Bean_Two) autoData).get_C_汽车之家_C_驾驶功能__匝道自动驶出_入());
//            autoBean.set_C_汽车之家_C_驾驶功能__远程召唤(((Bean_Two) autoData).get_C_汽车之家_C_驾驶功能__远程召唤());
//            autoBean.set_C_汽车之家_C_驾驶功能__夜视系统(((Bean_Two) autoData).get_C_汽车之家_C_驾驶功能__夜视系统());
//            autoBean.set_C_汽车之家_C_驾驶功能__遥控泊车(((Bean_Two) autoData).get_C_汽车之家_C_驾驶功能__遥控泊车());
//            autoBean.set_C_汽车之家_C_驾驶功能__循迹倒车(((Bean_Two) autoData).get_C_汽车之家_C_驾驶功能__循迹倒车());
//            autoBean.set_C_汽车之家_C_驾驶功能__巡航系统(((Bean_Two) autoData).get_C_汽车之家_C_驾驶功能__巡航系统());
//            autoBean.set_C_汽车之家_C_驾驶功能__高精地图(((Bean_Two) autoData).get_C_汽车之家_C_驾驶功能__高精地图());
//            autoBean.set_C_汽车之家_C_驾驶功能__辅助驾驶系统(((Bean_Two) autoData).get_C_汽车之家_C_驾驶功能__辅助驾驶系统());
//            autoBean.set_C_汽车之家_C_驾驶功能__辅助驾驶等级(((Bean_Two) autoData).get_C_汽车之家_C_驾驶功能__辅助驾驶等级());
//            autoBean.set_C_汽车之家_C_驾驶功能__道路交通标识识别(((Bean_Two) autoData).get_C_汽车之家_C_驾驶功能__道路交通标识识别());
//            autoBean.set_C_汽车之家_C_驾驶功能__车道居中保持(((Bean_Two) autoData).get_C_汽车之家_C_驾驶功能__车道居中保持());
//            autoBean.set_C_汽车之家_C_驾驶功能__车道保持辅助系统(((Bean_Two) autoData).get_C_汽车之家_C_驾驶功能__车道保持辅助系统());
//            autoBean.set_C_汽车之家_C_驾驶功能__并线辅助(((Bean_Two) autoData).get_C_汽车之家_C_驾驶功能__并线辅助());
//            autoBean.set_C_汽车之家_C_驾驶功能__AR实景导航(((Bean_Two) autoData).get_C_汽车之家_C_驾驶功能__AR实景导航());
//            autoBean.set_C_汽车之家_C_驾驶操控__自动驻车(((Bean_Two) autoData).get_C_汽车之家_C_驾驶操控__自动驻车());
//            autoBean.set_C_汽车之家_C_驾驶操控__整体主动转向系统(((Bean_Two) autoData).get_C_汽车之家_C_驾驶操控__整体主动转向系统());
//            autoBean.set_C_汽车之家_C_驾驶操控__上坡辅助(((Bean_Two) autoData).get_C_汽车之家_C_驾驶操控__上坡辅助());
//            autoBean.set_C_汽车之家_C_驾驶操控__可变转向比(((Bean_Two) autoData).get_C_汽车之家_C_驾驶操控__可变转向比());
//            autoBean.set_C_汽车之家_C_驾驶操控__可变悬架功能(((Bean_Two) autoData).get_C_汽车之家_C_驾驶操控__可变悬架功能());
//            autoBean.set_C_汽车之家_C_驾驶操控__驾驶模式切换(((Bean_Two) autoData).get_C_汽车之家_C_驾驶操控__驾驶模式切换());
//            autoBean.set_C_汽车之家_C_驾驶操控__发动机启停技术(((Bean_Two) autoData).get_C_汽车之家_C_驾驶操控__发动机启停技术());
//            autoBean.set_C_汽车之家_C_驾驶操控__陡坡缓降(((Bean_Two) autoData).get_C_汽车之家_C_驾驶操控__陡坡缓降());
//            autoBean.set_C_汽车之家_C_驾驶操控__单踏板模式(((Bean_Two) autoData).get_C_汽车之家_C_驾驶操控__单踏板模式());
//            autoBean.set_C_汽车之家_C_基本参数__最高车速_km_h(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__最高车速_km_h());
//            autoBean.set_C_汽车之家_C_基本参数__整车质保(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__整车质保());
//            autoBean.set_C_汽车之家_C_基本参数__长_宽_高_mm(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__长_宽_高_mm());
//            autoBean.set_C_汽车之家_C_基本参数__首任车主质保政策(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__首任车主质保政策());
//            autoBean.set_C_汽车之家_C_基本参数__上市时间(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__上市时间());
//            autoBean.set_C_汽车之家_C_基本参数__能源类型(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__能源类型());
//            autoBean.set_C_汽车之家_C_基本参数__级别(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__级别());
//            autoBean.set_C_汽车之家_C_基本参数__环保标准(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__环保标准());
//            autoBean.set_C_汽车之家_C_基本参数__官方0_100km_h加速_s(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__官方0_100km_h加速_s());
//            autoBean.set_C_汽车之家_C_基本参数__发动机(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__发动机());
//            autoBean.set_C_汽车之家_C_基本参数__电动机_Ps(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__电动机_Ps());
//            autoBean.set_C_汽车之家_C_基本参数__电池慢充时间_小时(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__电池慢充时间_小时());
//            autoBean.set_C_汽车之家_C_基本参数__电池慢充电量范围(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__电池慢充电量范围());
//            autoBean.set_C_汽车之家_C_基本参数__电池快充时间_小时(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__电池快充时间_小时());
//            autoBean.set_C_汽车之家_C_基本参数__电池快充电量范围(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__电池快充电量范围());
//            autoBean.set_C_汽车之家_C_基本参数__车型名称(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__车型名称());
//            autoBean.set_C_汽车之家_C_基本参数__车身结构(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__车身结构());
//            autoBean.set_C_汽车之家_C_基本参数__厂商指导价_元(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__厂商指导价_元());
//            autoBean.set_C_汽车之家_C_基本参数__厂商(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__厂商());
//            autoBean.set_C_汽车之家_C_基本参数__变速箱(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__变速箱());
//            autoBean.set_C_汽车之家_C_基本参数__WLTC综合油耗_L_100km(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__WLTC综合油耗_L_100km());
//            autoBean.set_C_汽车之家_C_基本参数__WLTC纯电续航里程_km(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__WLTC纯电续航里程_km());
//            autoBean.set_C_汽车之家_C_基本参数__NEDC综合油耗_L_100km(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__NEDC综合油耗_L_100km());
//            autoBean.set_C_汽车之家_C_基本参数__NEDC纯电续航里程_km(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__NEDC纯电续航里程_km());
//            autoBean.set_C_汽车之家_C_基本参数__EPA纯电续航里程_km(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__EPA纯电续航里程_km());
//            autoBean.set_C_汽车之家_C_基本参数__CLTC纯电续航里程_km(((Bean_Two) autoData).get_C_汽车之家_C_基本参数__CLTC纯电续航里程_km());
//            autoBean.set_C_汽车之家_C_方向盘_内后视镜__仪表盘屏幕像素密度(((Bean_Two) autoData).get_C_汽车之家_C_方向盘_内后视镜__仪表盘屏幕像素密度());
//            autoBean.set_C_汽车之家_C_方向盘_内后视镜__仪表盘屏幕分辨率_px(((Bean_Two) autoData).get_C_汽车之家_C_方向盘_内后视镜__仪表盘屏幕分辨率_px());
//            autoBean.set_C_汽车之家_C_方向盘_内后视镜__仪表盘屏幕材质(((Bean_Two) autoData).get_C_汽车之家_C_方向盘_内后视镜__仪表盘屏幕材质());
//            autoBean.set_C_汽车之家_C_方向盘_内后视镜__液晶仪表尺寸(((Bean_Two) autoData).get_C_汽车之家_C_方向盘_内后视镜__液晶仪表尺寸());
//            autoBean.set_C_汽车之家_C_方向盘_内后视镜__全液晶仪表盘(((Bean_Two) autoData).get_C_汽车之家_C_方向盘_内后视镜__全液晶仪表盘());
//            autoBean.set_C_汽车之家_C_方向盘_内后视镜__换挡形式(((Bean_Two) autoData).get_C_汽车之家_C_方向盘_内后视镜__换挡形式());
//            autoBean.set_C_汽车之家_C_方向盘_内后视镜__行车电脑显示屏幕(((Bean_Two) autoData).get_C_汽车之家_C_方向盘_内后视镜__行车电脑显示屏幕());
//            autoBean.set_C_汽车之家_C_方向盘_内后视镜__方向盘位置调节(((Bean_Two) autoData).get_C_汽车之家_C_方向盘_内后视镜__方向盘位置调节());
//            autoBean.set_C_汽车之家_C_方向盘_内后视镜__方向盘加热(((Bean_Two) autoData).get_C_汽车之家_C_方向盘_内后视镜__方向盘加热());
//            autoBean.set_C_汽车之家_C_方向盘_内后视镜__方向盘换挡(((Bean_Two) autoData).get_C_汽车之家_C_方向盘_内后视镜__方向盘换挡());
//            autoBean.set_C_汽车之家_C_方向盘_内后视镜__方向盘材质(((Bean_Two) autoData).get_C_汽车之家_C_方向盘_内后视镜__方向盘材质());
//            autoBean.set_C_汽车之家_C_方向盘_内后视镜__多功能方向盘(((Bean_Two) autoData).get_C_汽车之家_C_方向盘_内后视镜__多功能方向盘());
//            autoBean.set_C_汽车之家_C_方向盘_内后视镜__HUD抬头数字显示(((Bean_Two) autoData).get_C_汽车之家_C_方向盘_内后视镜__HUD抬头数字显示());
//            autoBean.set_C_汽车之家_C_方向盘_内后视镜__ETC装置(((Bean_Two) autoData).get_C_汽车之家_C_方向盘_内后视镜__ETC装置());
//            autoBean.set_C_汽车之家_C_发动机__最大扭矩转速_rpm(((Bean_Two) autoData).get_C_汽车之家_C_发动机__最大扭矩转速_rpm());
//            autoBean.set_C_汽车之家_C_发动机__最大扭矩_N_m(((Bean_Two) autoData).get_C_汽车之家_C_发动机__最大扭矩_N_m());
//            autoBean.set_C_汽车之家_C_发动机__最大马力_Ps(((Bean_Two) autoData).get_C_汽车之家_C_发动机__最大马力_Ps());
//            autoBean.set_C_汽车之家_C_发动机__最大净功率_kW(((Bean_Two) autoData).get_C_汽车之家_C_发动机__最大净功率_kW());
//            autoBean.set_C_汽车之家_C_发动机__最大功率转速_rpm(((Bean_Two) autoData).get_C_汽车之家_C_发动机__最大功率转速_rpm());
//            autoBean.set_C_汽车之家_C_发动机__最大功率_kW(((Bean_Two) autoData).get_C_汽车之家_C_发动机__最大功率_kW());
//            autoBean.set_C_汽车之家_C_发动机__压缩比(((Bean_Two) autoData).get_C_汽车之家_C_发动机__压缩比());
//            autoBean.set_C_汽车之家_C_发动机__推荐燃油标号(((Bean_Two) autoData).get_C_汽车之家_C_发动机__推荐燃油标号());
//            autoBean.set_C_汽车之家_C_发动机__气缸数_个(((Bean_Two) autoData).get_C_汽车之家_C_发动机__气缸数_个());
//            autoBean.set_C_汽车之家_C_发动机__气缸排列形式(((Bean_Two) autoData).get_C_汽车之家_C_发动机__气缸排列形式());
//            autoBean.set_C_汽车之家_C_发动机__配气机构(((Bean_Two) autoData).get_C_汽车之家_C_发动机__配气机构());
//            autoBean.set_C_汽车之家_C_发动机__排量_mL(((Bean_Two) autoData).get_C_汽车之家_C_发动机__排量_mL());
//            autoBean.set_C_汽车之家_C_发动机__排量_L(((Bean_Two) autoData).get_C_汽车之家_C_发动机__排量_L());
//            autoBean.set_C_汽车之家_C_发动机__每缸气门数_个(((Bean_Two) autoData).get_C_汽车之家_C_发动机__每缸气门数_个());
//            autoBean.set_C_汽车之家_C_发动机__进气形式(((Bean_Two) autoData).get_C_汽车之家_C_发动机__进气形式());
//            autoBean.set_C_汽车之家_C_发动机__环保标准(((Bean_Two) autoData).get_C_汽车之家_C_发动机__环保标准());
//            autoBean.set_C_汽车之家_C_发动机__供油方式(((Bean_Two) autoData).get_C_汽车之家_C_发动机__供油方式());
//            autoBean.set_C_汽车之家_C_发动机__缸体材料(((Bean_Two) autoData).get_C_汽车之家_C_发动机__缸体材料());
//            autoBean.set_C_汽车之家_C_发动机__缸盖材料(((Bean_Two) autoData).get_C_汽车之家_C_发动机__缸盖材料());
//            autoBean.set_C_汽车之家_C_发动机__发动机型号(((Bean_Two) autoData).get_C_汽车之家_C_发动机__发动机型号());
//            autoBean.set_C_汽车之家_C_发动机__发动机布局(((Bean_Two) autoData).get_C_汽车之家_C_发动机__发动机布局());
//            autoBean.set_C_汽车之家_C_电动机__系统综合扭矩_N_m(((Bean_Two) autoData).get_C_汽车之家_C_电动机__系统综合扭矩_N_m());
//            autoBean.set_C_汽车之家_C_电动机__系统综合功率_Ps(((Bean_Two) autoData).get_C_汽车之家_C_电动机__系统综合功率_Ps());
//            autoBean.set_C_汽车之家_C_电动机__系统综合功率_kW(((Bean_Two) autoData).get_C_汽车之家_C_电动机__系统综合功率_kW());
//            autoBean.set_C_汽车之家_C_电动机__驱动电机数(((Bean_Two) autoData).get_C_汽车之家_C_电动机__驱动电机数());
//            autoBean.set_C_汽车之家_C_电动机__前电动机最大扭矩_N_m(((Bean_Two) autoData).get_C_汽车之家_C_电动机__前电动机最大扭矩_N_m());
//            autoBean.set_C_汽车之家_C_电动机__前电动机最大功率_kW(((Bean_Two) autoData).get_C_汽车之家_C_电动机__前电动机最大功率_kW());
//            autoBean.set_C_汽车之家_C_电动机__慢充接口位置(((Bean_Two) autoData).get_C_汽车之家_C_电动机__慢充接口位置());
//            autoBean.set_C_汽车之家_C_电动机__快充接口位置(((Bean_Two) autoData).get_C_汽车之家_C_电动机__快充接口位置());
//            autoBean.set_C_汽车之家_C_电动机__快充功率_kW(((Bean_Two) autoData).get_C_汽车之家_C_电动机__快充功率_kW());
//            autoBean.set_C_汽车之家_C_电动机__换电(((Bean_Two) autoData).get_C_汽车之家_C_电动机__换电());
//            autoBean.set_C_汽车之家_C_电动机__后电动机最大扭矩_N_m(((Bean_Two) autoData).get_C_汽车之家_C_电动机__后电动机最大扭矩_N_m());
//            autoBean.set_C_汽车之家_C_电动机__后电动机最大功率_kW(((Bean_Two) autoData).get_C_汽车之家_C_电动机__后电动机最大功率_kW());
//            autoBean.set_C_汽车之家_C_电动机__电芯品牌(((Bean_Two) autoData).get_C_汽车之家_C_电动机__电芯品牌());
//            autoBean.set_C_汽车之家_C_电动机__电机类型(((Bean_Two) autoData).get_C_汽车之家_C_电动机__电机类型());
//            autoBean.set_C_汽车之家_C_电动机__电机布局(((Bean_Two) autoData).get_C_汽车之家_C_电动机__电机布局());
//            autoBean.set_C_汽车之家_C_电动机__电动机总扭矩_N_m(((Bean_Two) autoData).get_C_汽车之家_C_电动机__电动机总扭矩_N_m());
//            autoBean.set_C_汽车之家_C_电动机__电动机总马力_Ps(((Bean_Two) autoData).get_C_汽车之家_C_电动机__电动机总马力_Ps());
//            autoBean.set_C_汽车之家_C_电动机__电动机总功率_kW(((Bean_Two) autoData).get_C_汽车之家_C_电动机__电动机总功率_kW());
//            autoBean.set_C_汽车之家_C_电动机__电池组质保(((Bean_Two) autoData).get_C_汽车之家_C_电动机__电池组质保());
//            autoBean.set_C_汽车之家_C_电动机__电池能量密度_Wh_kg(((Bean_Two) autoData).get_C_汽车之家_C_电动机__电池能量密度_Wh_kg());
//            autoBean.set_C_汽车之家_C_电动机__电池能量_kWh(((Bean_Two) autoData).get_C_汽车之家_C_电动机__电池能量_kWh());
//            autoBean.set_C_汽车之家_C_电动机__电池慢充时间_小时(((Bean_Two) autoData).get_C_汽车之家_C_电动机__电池慢充时间_小时());
//            autoBean.set_C_汽车之家_C_电动机__电池慢充电量范围(((Bean_Two) autoData).get_C_汽车之家_C_电动机__电池慢充电量范围());
//            autoBean.set_C_汽车之家_C_电动机__电池类型(((Bean_Two) autoData).get_C_汽车之家_C_电动机__电池类型());
//            autoBean.set_C_汽车之家_C_电动机__电池快充时间_小时(((Bean_Two) autoData).get_C_汽车之家_C_电动机__电池快充时间_小时());
//            autoBean.set_C_汽车之家_C_电动机__电池快充电量范围(((Bean_Two) autoData).get_C_汽车之家_C_电动机__电池快充电量范围());
//            autoBean.set_C_汽车之家_C_电动机__百公里耗电量_kWh_100km(((Bean_Two) autoData).get_C_汽车之家_C_电动机__百公里耗电量_kWh_100km());
//            autoBean.set_C_汽车之家_C_电动机__WLTP纯电续航里程_km(((Bean_Two) autoData).get_C_汽车之家_C_电动机__WLTP纯电续航里程_km());
//            autoBean.set_C_汽车之家_C_电动机__WLTC综合续航_km(((Bean_Two) autoData).get_C_汽车之家_C_电动机__WLTC综合续航_km());
//            autoBean.set_C_汽车之家_C_电动机__NEDC综合续航_km(((Bean_Two) autoData).get_C_汽车之家_C_电动机__NEDC综合续航_km());
//            autoBean.set_C_汽车之家_C_电动机__NEDC纯电续航里程_km(((Bean_Two) autoData).get_C_汽车之家_C_电动机__NEDC纯电续航里程_km());
//            autoBean.set_C_汽车之家_C_电动机__EPA纯电续航里程_km(((Bean_Two) autoData).get_C_汽车之家_C_电动机__EPA纯电续航里程_km());
//            autoBean.set_C_汽车之家_C_电动机__CLTC综合续航_km(((Bean_Two) autoData).get_C_汽车之家_C_电动机__CLTC综合续航_km());
//            autoBean.set_C_汽车之家_C_电动机__CLTC纯电续航里程_km(((Bean_Two) autoData).get_C_汽车之家_C_电动机__CLTC纯电续航里程_km());
//            autoBean.set_C_汽车之家_C_底盘转向__助力类型(((Bean_Two) autoData).get_C_汽车之家_C_底盘转向__助力类型());
//            autoBean.set_C_汽车之家_C_底盘转向__中央差速器结构(((Bean_Two) autoData).get_C_汽车之家_C_底盘转向__中央差速器结构());
//            autoBean.set_C_汽车之家_C_底盘转向__四驱形式(((Bean_Two) autoData).get_C_汽车之家_C_底盘转向__四驱形式());
//            autoBean.set_C_汽车之家_C_底盘转向__驱动方式(((Bean_Two) autoData).get_C_汽车之家_C_底盘转向__驱动方式());
//            autoBean.set_C_汽车之家_C_底盘转向__前悬架类型(((Bean_Two) autoData).get_C_汽车之家_C_底盘转向__前悬架类型());
//            autoBean.set_C_汽车之家_C_底盘转向__后悬架类型(((Bean_Two) autoData).get_C_汽车之家_C_底盘转向__后悬架类型());
//            autoBean.set_C_汽车之家_C_底盘转向__车体结构(((Bean_Two) autoData).get_C_汽车之家_C_底盘转向__车体结构());
//            autoBean.set_C_汽车之家_C_车外灯光__转向辅助灯(((Bean_Two) autoData).get_C_汽车之家_C_车外灯光__转向辅助灯());
//            autoBean.set_C_汽车之家_C_车外灯光__远光灯光源(((Bean_Two) autoData).get_C_汽车之家_C_车外灯光__远光灯光源());
//            autoBean.set_C_汽车之家_C_车外灯光__近光灯光源(((Bean_Two) autoData).get_C_汽车之家_C_车外灯光__近光灯光源());
//            autoBean.set_C_汽车之家_C_车外灯光__灯光特色功能(((Bean_Two) autoData).get_C_汽车之家_C_车外灯光__灯光特色功能());
//            autoBean.set_C_汽车之家_C_车外灯光__大灯清洗装置(((Bean_Two) autoData).get_C_汽车之家_C_车外灯光__大灯清洗装置());
//            autoBean.set_C_汽车之家_C_车外灯光__车前雾灯(((Bean_Two) autoData).get_C_汽车之家_C_车外灯光__车前雾灯());
//            autoBean.set_C_汽车之家_C_车外灯光__LED日间行车灯(((Bean_Two) autoData).get_C_汽车之家_C_车外灯光__LED日间行车灯());
//            autoBean.set_C_汽车之家_C_车身__座位数_个(((Bean_Two) autoData).get_C_汽车之家_C_车身__座位数_个());
//            autoBean.set_C_汽车之家_C_车身__最小转弯半径_m(((Bean_Two) autoData).get_C_汽车之家_C_车身__最小转弯半径_m());
//            autoBean.set_C_汽车之家_C_车身__最大载重质量_kg(((Bean_Two) autoData).get_C_汽车之家_C_车身__最大载重质量_kg());
//            autoBean.set_C_汽车之家_C_车身__最大涉水深度_mm(((Bean_Two) autoData).get_C_汽车之家_C_车身__最大涉水深度_mm());
//            autoBean.set_C_汽车之家_C_车身__最大爬坡度(((Bean_Two) autoData).get_C_汽车之家_C_车身__最大爬坡度());
//            autoBean.set_C_汽车之家_C_车身__轴距_mm(((Bean_Two) autoData).get_C_汽车之家_C_车身__轴距_mm());
//            autoBean.set_C_汽车之家_C_车身__长度_mm(((Bean_Two) autoData).get_C_汽车之家_C_车身__长度_mm());
//            autoBean.set_C_汽车之家_C_车身__油箱容积_L(((Bean_Two) autoData).get_C_汽车之家_C_车身__油箱容积_L());
//            autoBean.set_C_汽车之家_C_车身__前轮距_mm(((Bean_Two) autoData).get_C_汽车之家_C_车身__前轮距_mm());
//            autoBean.set_C_汽车之家_C_车身__前备厢容积_L(((Bean_Two) autoData).get_C_汽车之家_C_车身__前备厢容积_L());
//            autoBean.set_C_汽车之家_C_车身__气罐容积_L(((Bean_Two) autoData).get_C_汽车之家_C_车身__气罐容积_L());
//            autoBean.set_C_汽车之家_C_车身__满载最小离地间隙_mm(((Bean_Two) autoData).get_C_汽车之家_C_车身__满载最小离地间隙_mm());
//            autoBean.set_C_汽车之家_C_车身__离去角(((Bean_Two) autoData).get_C_汽车之家_C_车身__离去角());
//            autoBean.set_C_汽车之家_C_车身__宽度_mm(((Bean_Two) autoData).get_C_汽车之家_C_车身__宽度_mm());
//            autoBean.set_C_汽车之家_C_车身__空载最小离地间隙_mm(((Bean_Two) autoData).get_C_汽车之家_C_车身__空载最小离地间隙_mm());
//            autoBean.set_C_汽车之家_C_车身__接近角(((Bean_Two) autoData).get_C_汽车之家_C_车身__接近角());
//            autoBean.set_C_汽车之家_C_车身__货箱尺寸_mm(((Bean_Two) autoData).get_C_汽车之家_C_车身__货箱尺寸_mm());
//            autoBean.set_C_汽车之家_C_车身__后轮距_mm(((Bean_Two) autoData).get_C_汽车之家_C_车身__后轮距_mm());
//            autoBean.set_C_汽车之家_C_车身__后备厢容积_L(((Bean_Two) autoData).get_C_汽车之家_C_车身__后备厢容积_L());
//            autoBean.set_C_汽车之家_C_车身__高度_mm(((Bean_Two) autoData).get_C_汽车之家_C_车身__高度_mm());
//            autoBean.set_C_汽车之家_C_车身__风阻系数_Cd(((Bean_Two) autoData).get_C_汽车之家_C_车身__风阻系数_Cd());
//            autoBean.set_C_汽车之家_C_车身__车门数_个(((Bean_Two) autoData).get_C_汽车之家_C_车身__车门数_个());
//            autoBean.set_C_汽车之家_C_车身__车门开启方式(((Bean_Two) autoData).get_C_汽车之家_C_车身__车门开启方式());
//            autoBean.set_C_汽车之家_C_车内充电__手机无线充电功能(((Bean_Two) autoData).get_C_汽车之家_C_车内充电__手机无线充电功能());
//            autoBean.set_C_汽车之家_C_车内充电__行李厢12V电源接口(((Bean_Two) autoData).get_C_汽车之家_C_车内充电__行李厢12V电源接口());
//            autoBean.set_C_汽车之家_C_车内充电__多媒体_充电接口(((Bean_Two) autoData).get_C_汽车之家_C_车内充电__多媒体_充电接口());
//            autoBean.set_C_汽车之家_C_车内充电__USB_Type_C接口数量(((Bean_Two) autoData).get_C_汽车之家_C_车内充电__USB_Type_C接口数量());
//            autoBean.set_C_汽车之家_C_车内充电__220V_230V电源(((Bean_Two) autoData).get_C_汽车之家_C_车内充电__220V_230V电源());
//            autoBean.set_C_汽车之家_C_车轮制动__驻车制动类型(((Bean_Two) autoData).get_C_汽车之家_C_车轮制动__驻车制动类型());
//            autoBean.set_C_汽车之家_C_车轮制动__前制动器类型(((Bean_Two) autoData).get_C_汽车之家_C_车轮制动__前制动器类型());
//            autoBean.set_C_汽车之家_C_车轮制动__前轮胎规格(((Bean_Two) autoData).get_C_汽车之家_C_车轮制动__前轮胎规格());
//            autoBean.set_C_汽车之家_C_车轮制动__后制动器类型(((Bean_Two) autoData).get_C_汽车之家_C_车轮制动__后制动器类型());
//            autoBean.set_C_汽车之家_C_车轮制动__后轮胎规格(((Bean_Two) autoData).get_C_汽车之家_C_车轮制动__后轮胎规格());
//            autoBean.set_C_汽车之家_C_车轮制动__备胎规格(((Bean_Two) autoData).get_C_汽车之家_C_车轮制动__备胎规格());
//            autoBean.set_C_汽车之家_C_车轮制动__备胎放置方式(((Bean_Two) autoData).get_C_汽车之家_C_车轮制动__备胎放置方式());
//            autoBean.set_C_汽车之家_C_被动安全__主_副驾驶座安全气囊(((Bean_Two) autoData).get_C_汽车之家_C_被动安全__主_副驾驶座安全气囊());
//            autoBean.set_C_汽车之家_C_被动安全__膝部气囊(((Bean_Two) autoData).get_C_汽车之家_C_被动安全__膝部气囊());
//            autoBean.set_C_汽车之家_C_被动安全__缺气保用轮胎(((Bean_Two) autoData).get_C_汽车之家_C_被动安全__缺气保用轮胎());
//            autoBean.set_C_汽车之家_C_被动安全__前_后排侧气囊(((Bean_Two) autoData).get_C_汽车之家_C_被动安全__前_后排侧气囊());
//            autoBean.set_C_汽车之家_C_被动安全__后排座椅防下滑气囊(((Bean_Two) autoData).get_C_汽车之家_C_被动安全__后排座椅防下滑气囊());
//            autoBean.set_C_汽车之家_C_被动安全__后排安全带式气囊(((Bean_Two) autoData).get_C_汽车之家_C_被动安全__后排安全带式气囊());
//            autoBean.set_C_汽车之家_C_被动安全__副驾驶座垫式气囊(((Bean_Two) autoData).get_C_汽车之家_C_被动安全__副驾驶座垫式气囊());
//            autoBean.set_C_汽车之家_C_被动安全__被动行人保护(((Bean_Two) autoData).get_C_汽车之家_C_被动安全__被动行人保护());
//            dataList.add(autoBean);
//        }
//        System.out.println(dataList.size());
//        insertCompare.insert_除匹配的数据(dataList);
//        dataList.clear();
        ArrayList<Object> ycDataList = compare.get_除匹配上的易车数据();
        for (Object yiCheData : ycDataList) {
            Bean_Two autoBean = new Bean_Two();
            autoBean.set_C_汽车之家的版本Id(((Bean_Two) yiCheData).get_C_汽车之家的版本Id());
            autoBean.set_C_易车的版本Id(((Bean_Two) yiCheData).get_C_易车的版本Id());
//            autoBean.set_C_汽车之家版本Id_易车版本Id(((Bean_Two) yiCheData).get_C_汽车之家版本Id_易车版本Id());
            autoBean.set_C_易车_C_座椅配置__座椅材质(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__座椅材质());
            autoBean.set_C_易车_C_座椅配置__座椅布局(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__座椅布局());
            autoBean.set_C_易车_C_座椅配置__主座椅调节方式(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__主座椅调节方式());
            autoBean.set_C_易车_C_座椅配置__主_副驾驶座电动调节(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__主_副驾驶座电动调节());
            autoBean.set_C_易车_C_座椅配置__运动风格座椅(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__运动风格座椅());
            autoBean.set_C_易车_C_座椅配置__零重力座椅(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__零重力座椅());
            autoBean.set_C_易车_C_座椅配置__加热_制冷杯架(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__加热_制冷杯架());
            autoBean.set_C_易车_C_座椅配置__后排座椅放倒形式(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__后排座椅放倒形式());
            autoBean.set_C_易车_C_座椅配置__后排座椅电动放倒(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__后排座椅电动放倒());
            autoBean.set_C_易车_C_座椅配置__后排小桌板(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__后排小桌板());
            autoBean.set_C_易车_C_座椅配置__后排杯架(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__后排杯架());
            autoBean.set_C_易车_C_座椅配置__副座椅调节方式(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__副座椅调节方式());
            autoBean.set_C_易车_C_座椅配置__福祉座椅(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__福祉座椅());
            autoBean.set_C_易车_C_座椅配置__第三排座椅调节(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__第三排座椅调节());
            autoBean.set_C_易车_C_座椅配置__第三排座椅功能(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__第三排座椅功能());
            autoBean.set_C_易车_C_座椅配置__第三排座椅电动调节(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__第三排座椅电动调节());
            autoBean.set_C_易车_C_座椅配置__第二排座椅调节(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__第二排座椅调节());
            autoBean.set_C_易车_C_座椅配置__第二排座椅功能(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__第二排座椅功能());
            autoBean.set_C_易车_C_座椅配置__第二排座椅电动调节(((Bean_Two) yiCheData).get_C_易车_C_座椅配置__第二排座椅电动调节());
            autoBean.set_C_易车_C_主动安全__主动刹车_主动安全系统(((Bean_Two) yiCheData).get_C_易车_C_主动安全__主动刹车_主动安全系统());
            autoBean.set_C_易车_C_主动安全__制动力分配_EBD_CBC等(((Bean_Two) yiCheData).get_C_易车_C_主动安全__制动力分配_EBD_CBC等());
            autoBean.set_C_易车_C_主动安全__胎压监测功能(((Bean_Two) yiCheData).get_C_易车_C_主动安全__胎压监测功能());
            autoBean.set_C_易车_C_主动安全__哨兵模式_千里眼(((Bean_Two) yiCheData).get_C_易车_C_主动安全__哨兵模式_千里眼());
            autoBean.set_C_易车_C_主动安全__前方碰撞预警(((Bean_Two) yiCheData).get_C_易车_C_主动安全__前方碰撞预警());
            autoBean.set_C_易车_C_主动安全__牵引力控制_ASR_TCS_TRC等(((Bean_Two) yiCheData).get_C_易车_C_主动安全__牵引力控制_ASR_TCS_TRC等());
            autoBean.set_C_易车_C_主动安全__疲劳驾驶提示(((Bean_Two) yiCheData).get_C_易车_C_主动安全__疲劳驾驶提示());
            autoBean.set_C_易车_C_主动安全__内置行车记录仪(((Bean_Two) yiCheData).get_C_易车_C_主动安全__内置行车记录仪());
            autoBean.set_C_易车_C_主动安全__后方碰撞预警(((Bean_Two) yiCheData).get_C_易车_C_主动安全__后方碰撞预警());
            autoBean.set_C_易车_C_主动安全__防侧翻系统(((Bean_Two) yiCheData).get_C_易车_C_主动安全__防侧翻系统());
            autoBean.set_C_易车_C_主动安全__低速行车警告(((Bean_Two) yiCheData).get_C_易车_C_主动安全__低速行车警告());
            autoBean.set_C_易车_C_主动安全__道路救援呼叫(((Bean_Two) yiCheData).get_C_易车_C_主动安全__道路救援呼叫());
            autoBean.set_C_易车_C_主动安全__车身稳定控制_ESC_ESP_DSC等(((Bean_Two) yiCheData).get_C_易车_C_主动安全__车身稳定控制_ESC_ESP_DSC等());
            autoBean.set_C_易车_C_主动安全__刹车辅助_EBA_BAS_BA等(((Bean_Two) yiCheData).get_C_易车_C_主动安全__刹车辅助_EBA_BAS_BA等());
            autoBean.set_C_易车_C_主动安全__安全带未系提醒(((Bean_Two) yiCheData).get_C_易车_C_主动安全__安全带未系提醒());
            autoBean.set_C_易车_C_主动安全__ISOFIX儿童座椅接口(((Bean_Two) yiCheData).get_C_易车_C_主动安全__ISOFIX儿童座椅接口());
            autoBean.set_C_易车_C_主动安全__ABS防抱死(((Bean_Two) yiCheData).get_C_易车_C_主动安全__ABS防抱死());
            autoBean.set_C_易车_C_智能化配置__主动降噪(((Bean_Two) yiCheData).get_C_易车_C_智能化配置__主动降噪());
            autoBean.set_C_易车_C_智能化配置__模拟声浪(((Bean_Two) yiCheData).get_C_易车_C_智能化配置__模拟声浪());
            autoBean.set_C_易车_C_智能化配置__车内生物监测系统(((Bean_Two) yiCheData).get_C_易车_C_智能化配置__车内生物监测系统());
            autoBean.set_C_易车_C_智能化配置__V2X通讯(((Bean_Two) yiCheData).get_C_易车_C_智能化配置__V2X通讯());
            autoBean.set_C_易车_C_智能化配置__OTA升级(((Bean_Two) yiCheData).get_C_易车_C_智能化配置__OTA升级());
            autoBean.set_C_易车_C_音响_车内灯光__主动式环境氛围灯(((Bean_Two) yiCheData).get_C_易车_C_音响_车内灯光__主动式环境氛围灯());
            autoBean.set_C_易车_C_音响_车内灯光__扬声器数量(((Bean_Two) yiCheData).get_C_易车_C_音响_车内灯光__扬声器数量());
            autoBean.set_C_易车_C_音响_车内灯光__车内环境氛围灯(((Bean_Two) yiCheData).get_C_易车_C_音响_车内灯光__车内环境氛围灯());
            autoBean.set_C_易车_C_外观_防盗__自动开合车门(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__自动开合车门());
            autoBean.set_C_易车_C_外观_防盗__主动闭合式进气格栅(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__主动闭合式进气格栅());
            autoBean.set_C_易车_C_外观_防盗__整车无线充电(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__整车无线充电());
            autoBean.set_C_易车_C_外观_防盗__隐藏电动门把手(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__隐藏电动门把手());
            autoBean.set_C_易车_C_外观_防盗__钥匙类型(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__钥匙类型());
            autoBean.set_C_易车_C_外观_防盗__无钥匙启动系统(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__无钥匙启动系统());
            autoBean.set_C_易车_C_外观_防盗__无钥匙进入功能(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__无钥匙进入功能());
            autoBean.set_C_易车_C_外观_防盗__无框设计车门(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__无框设计车门());
            autoBean.set_C_易车_C_外观_防盗__尾门玻璃独立开启(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__尾门玻璃独立开启());
            autoBean.set_C_易车_C_外观_防盗__外观套件(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__外观套件());
            autoBean.set_C_易车_C_外观_防盗__轮圈材质(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__轮圈材质());
            autoBean.set_C_易车_C_外观_防盗__感应后备厢(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__感应后备厢());
            autoBean.set_C_易车_C_外观_防盗__对外放电(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__对外放电());
            autoBean.set_C_易车_C_外观_防盗__电动吸合车门(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__电动吸合车门());
            autoBean.set_C_易车_C_外观_防盗__电动扰流板(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__电动扰流板());
            autoBean.set_C_易车_C_外观_防盗__电动后备厢位置记忆(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__电动后备厢位置记忆());
            autoBean.set_C_易车_C_外观_防盗__电动后备厢(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__电动后备厢());
            autoBean.set_C_易车_C_外观_防盗__车顶行李架(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__车顶行李架());
            autoBean.set_C_易车_C_外观_防盗__车侧脚踏板(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__车侧脚踏板());
            autoBean.set_C_易车_C_外观_防盗__侧滑门形式(((Bean_Two) yiCheData).get_C_易车_C_外观_防盗__侧滑门形式());
            autoBean.set_C_易车_C_天窗_玻璃__天窗类型(((Bean_Two) yiCheData).get_C_易车_C_天窗_玻璃__天窗类型());
            autoBean.set_C_易车_C_天窗_玻璃__可加热喷水嘴(((Bean_Two) yiCheData).get_C_易车_C_天窗_玻璃__可加热喷水嘴());
            autoBean.set_C_易车_C_天窗_玻璃__后雨刷(((Bean_Two) yiCheData).get_C_易车_C_天窗_玻璃__后雨刷());
            autoBean.set_C_易车_C_天窗_玻璃__后排侧隐私玻璃(((Bean_Two) yiCheData).get_C_易车_C_天窗_玻璃__后排侧隐私玻璃());
            autoBean.set_C_易车_C_天窗_玻璃__后排侧窗遮阳帘(((Bean_Two) yiCheData).get_C_易车_C_天窗_玻璃__后排侧窗遮阳帘());
            autoBean.set_C_易车_C_天窗_玻璃__后风挡遮阳帘(((Bean_Two) yiCheData).get_C_易车_C_天窗_玻璃__后风挡遮阳帘());
            autoBean.set_C_易车_C_天窗_玻璃__光感天幕(((Bean_Two) yiCheData).get_C_易车_C_天窗_玻璃__光感天幕());
            autoBean.set_C_易车_C_天窗_玻璃__感应雨刷功能(((Bean_Two) yiCheData).get_C_易车_C_天窗_玻璃__感应雨刷功能());
            autoBean.set_C_易车_C_天窗_玻璃__车内化妆镜(((Bean_Two) yiCheData).get_C_易车_C_天窗_玻璃__车内化妆镜());
            autoBean.set_C_易车_C_天窗_玻璃__车窗一键升降功能(((Bean_Two) yiCheData).get_C_易车_C_天窗_玻璃__车窗一键升降功能());
            autoBean.set_C_易车_C_天窗_玻璃__车窗防夹手功能(((Bean_Two) yiCheData).get_C_易车_C_天窗_玻璃__车窗防夹手功能());
            autoBean.set_C_易车_C_天窗_玻璃__侧窗多层隔音玻璃(((Bean_Two) yiCheData).get_C_易车_C_天窗_玻璃__侧窗多层隔音玻璃());
            autoBean.set_C_易车_C_四驱_越野__限滑差速器_差速锁(((Bean_Two) yiCheData).get_C_易车_C_四驱_越野__限滑差速器_差速锁());
            autoBean.set_C_易车_C_四驱_越野__拖挂钩(((Bean_Two) yiCheData).get_C_易车_C_四驱_越野__拖挂钩());
            autoBean.set_C_易车_C_四驱_越野__拖车取电口(((Bean_Two) yiCheData).get_C_易车_C_四驱_越野__拖车取电口());
            autoBean.set_C_易车_C_四驱_越野__坦克转弯(((Bean_Two) yiCheData).get_C_易车_C_四驱_越野__坦克转弯());
            autoBean.set_C_易车_C_四驱_越野__涉水感应系统(((Bean_Two) yiCheData).get_C_易车_C_四驱_越野__涉水感应系统());
            autoBean.set_C_易车_C_四驱_越野__蠕行模式(((Bean_Two) yiCheData).get_C_易车_C_四驱_越野__蠕行模式());
            autoBean.set_C_易车_C_四驱_越野__低速四驱(((Bean_Two) yiCheData).get_C_易车_C_四驱_越野__低速四驱());
            autoBean.set_C_易车_C_屏幕_系统__中控下屏幕像素密度(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__中控下屏幕像素密度());
            autoBean.set_C_易车_C_屏幕_系统__中控下屏幕类型(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__中控下屏幕类型());
            autoBean.set_C_易车_C_屏幕_系统__中控下屏幕分辨率(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__中控下屏幕分辨率());
            autoBean.set_C_易车_C_屏幕_系统__中控下屏幕尺寸(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__中控下屏幕尺寸());
            autoBean.set_C_易车_C_屏幕_系统__中控屏幕像素密度(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__中控屏幕像素密度());
            autoBean.set_C_易车_C_屏幕_系统__中控屏幕类型(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__中控屏幕类型());
            autoBean.set_C_易车_C_屏幕_系统__中控屏幕分辨率(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__中控屏幕分辨率());
            autoBean.set_C_易车_C_屏幕_系统__中控屏幕尺寸(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__中控屏幕尺寸());
            autoBean.set_C_易车_C_屏幕_系统__中控彩色屏幕(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__中控彩色屏幕());
            autoBean.set_C_易车_C_屏幕_系统__语音助手唤醒词(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__语音助手唤醒词());
            autoBean.set_C_易车_C_屏幕_系统__语音识别控制系统(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__语音识别控制系统());
            autoBean.set_C_易车_C_屏幕_系统__语音免唤醒词(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__语音免唤醒词());
            autoBean.set_C_易车_C_屏幕_系统__语音连续识别(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__语音连续识别());
            autoBean.set_C_易车_C_屏幕_系统__语音分区域唤醒识别(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__语音分区域唤醒识别());
            autoBean.set_C_易车_C_屏幕_系统__应用商店(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__应用商店());
            autoBean.set_C_易车_C_屏幕_系统__手势控制(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__手势控制());
            autoBean.set_C_易车_C_屏幕_系统__手机互联_映射(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__手机互联_映射());
            autoBean.set_C_易车_C_屏幕_系统__面部识别(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__面部识别());
            autoBean.set_C_易车_C_屏幕_系统__蓝牙_车载电话(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__蓝牙_车载电话());
            autoBean.set_C_易车_C_屏幕_系统__后排液晶屏幕像素密度(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__后排液晶屏幕像素密度());
            autoBean.set_C_易车_C_屏幕_系统__后排液晶屏幕分辨率(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__后排液晶屏幕分辨率());
            autoBean.set_C_易车_C_屏幕_系统__后排液晶屏幕尺寸(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__后排液晶屏幕尺寸());
            autoBean.set_C_易车_C_屏幕_系统__后排液晶屏幕(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__后排液晶屏幕());
            autoBean.set_C_易车_C_屏幕_系统__后排控制多媒体(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__后排控制多媒体());
            autoBean.set_C_易车_C_屏幕_系统__后排多媒体屏幕数量(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__后排多媒体屏幕数量());
            autoBean.set_C_易车_C_屏幕_系统__副驾娱乐屏尺寸(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__副驾娱乐屏尺寸());
            autoBean.set_C_易车_C_屏幕_系统__副驾屏幕像素密度(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__副驾屏幕像素密度());
            autoBean.set_C_易车_C_屏幕_系统__副驾屏幕类型(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__副驾屏幕类型());
            autoBean.set_C_易车_C_屏幕_系统__副驾屏幕分辨率(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__副驾屏幕分辨率());
            autoBean.set_C_易车_C_屏幕_系统__多指飞屏操控(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__多指飞屏操控());
            autoBean.set_C_易车_C_屏幕_系统__车载CD_DVD(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__车载CD_DVD());
            autoBean.set_C_易车_C_屏幕_系统__车机智能芯片(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__车机智能芯片());
            autoBean.set_C_易车_C_屏幕_系统__车机系统内存_GB(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__车机系统内存_GB());
            autoBean.set_C_易车_C_屏幕_系统__车机系统存储_GB(((Bean_Two) yiCheData).get_C_易车_C_屏幕_系统__车机系统存储_GB());
            autoBean.set_C_易车_C_空调_冰箱__热泵空调(((Bean_Two) yiCheData).get_C_易车_C_空调_冰箱__热泵空调());
            autoBean.set_C_易车_C_空调_冰箱__空气质量监测(((Bean_Two) yiCheData).get_C_易车_C_空调_冰箱__空气质量监测());
            autoBean.set_C_易车_C_空调_冰箱__负离子发生器(((Bean_Two) yiCheData).get_C_易车_C_空调_冰箱__负离子发生器());
            autoBean.set_C_易车_C_空调_冰箱__车载空气净化器(((Bean_Two) yiCheData).get_C_易车_C_空调_冰箱__车载空气净化器());
            autoBean.set_C_易车_C_空调_冰箱__车载冰箱(((Bean_Two) yiCheData).get_C_易车_C_空调_冰箱__车载冰箱());
            autoBean.set_C_易车_C_空调_冰箱__车内香氛装置(((Bean_Two) yiCheData).get_C_易车_C_空调_冰箱__车内香氛装置());
            autoBean.set_C_易车_C_空调_冰箱__车内PM2_5过滤装置(((Bean_Two) yiCheData).get_C_易车_C_空调_冰箱__车内PM2_5过滤装置());
            autoBean.set_C_易车_C_驾驶硬件__前方感知摄像头像素(((Bean_Two) yiCheData).get_C_易车_C_驾驶硬件__前方感知摄像头像素());
            autoBean.set_C_易车_C_驾驶硬件__前方感知摄像头(((Bean_Two) yiCheData).get_C_易车_C_驾驶硬件__前方感知摄像头());
            autoBean.set_C_易车_C_驾驶硬件__前_后驻车雷达(((Bean_Two) yiCheData).get_C_易车_C_驾驶硬件__前_后驻车雷达());
            autoBean.set_C_易车_C_驾驶硬件__驾驶辅助影像(((Bean_Two) yiCheData).get_C_易车_C_驾驶硬件__驾驶辅助影像());
            autoBean.set_C_易车_C_驾驶硬件__激光雷达型号(((Bean_Two) yiCheData).get_C_易车_C_驾驶硬件__激光雷达型号());
            autoBean.set_C_易车_C_驾驶硬件__激光雷达线数(((Bean_Two) yiCheData).get_C_易车_C_驾驶硬件__激光雷达线数());
            autoBean.set_C_易车_C_驾驶硬件__激光雷达数量(((Bean_Two) yiCheData).get_C_易车_C_驾驶硬件__激光雷达数量());
            autoBean.set_C_易车_C_驾驶硬件__激光雷达品牌(((Bean_Two) yiCheData).get_C_易车_C_驾驶硬件__激光雷达品牌());
            autoBean.set_C_易车_C_驾驶硬件__激光雷达点云数量(((Bean_Two) yiCheData).get_C_易车_C_驾驶硬件__激光雷达点云数量());
            autoBean.set_C_易车_C_驾驶硬件__激光雷达10_反射率探测距离(((Bean_Two) yiCheData).get_C_易车_C_驾驶硬件__激光雷达10_反射率探测距离());
            autoBean.set_C_易车_C_驾驶硬件__环视摄像头像素(((Bean_Two) yiCheData).get_C_易车_C_驾驶硬件__环视摄像头像素());
            autoBean.set_C_易车_C_驾驶硬件__环境感知摄像头像素(((Bean_Two) yiCheData).get_C_易车_C_驾驶硬件__环境感知摄像头像素());
            autoBean.set_C_易车_C_驾驶硬件__毫米波雷达数量(((Bean_Two) yiCheData).get_C_易车_C_驾驶硬件__毫米波雷达数量());
            autoBean.set_C_易车_C_驾驶硬件__辅助驾驶芯片(((Bean_Two) yiCheData).get_C_易车_C_驾驶硬件__辅助驾驶芯片());
            autoBean.set_C_易车_C_驾驶硬件__车内摄像头数量(((Bean_Two) yiCheData).get_C_易车_C_驾驶硬件__车内摄像头数量());
            autoBean.set_C_易车_C_驾驶硬件__超声波雷达数量(((Bean_Two) yiCheData).get_C_易车_C_驾驶硬件__超声波雷达数量());
            autoBean.set_C_易车_C_驾驶功能__自动泊车入位(((Bean_Two) yiCheData).get_C_易车_C_驾驶功能__自动泊车入位());
            autoBean.set_C_易车_C_驾驶功能__自动变道辅助(((Bean_Two) yiCheData).get_C_易车_C_驾驶功能__自动变道辅助());
            autoBean.set_C_易车_C_驾驶功能__匝道自动驶出_入(((Bean_Two) yiCheData).get_C_易车_C_驾驶功能__匝道自动驶出_入());
            autoBean.set_C_易车_C_驾驶功能__远程召唤(((Bean_Two) yiCheData).get_C_易车_C_驾驶功能__远程召唤());
            autoBean.set_C_易车_C_驾驶功能__夜视系统(((Bean_Two) yiCheData).get_C_易车_C_驾驶功能__夜视系统());
            autoBean.set_C_易车_C_驾驶功能__遥控泊车(((Bean_Two) yiCheData).get_C_易车_C_驾驶功能__遥控泊车());
            autoBean.set_C_易车_C_驾驶功能__循迹倒车(((Bean_Two) yiCheData).get_C_易车_C_驾驶功能__循迹倒车());
            autoBean.set_C_易车_C_驾驶功能__巡航系统(((Bean_Two) yiCheData).get_C_易车_C_驾驶功能__巡航系统());
            autoBean.set_C_易车_C_驾驶功能__高精地图(((Bean_Two) yiCheData).get_C_易车_C_驾驶功能__高精地图());
            autoBean.set_C_易车_C_驾驶功能__辅助驾驶系统(((Bean_Two) yiCheData).get_C_易车_C_驾驶功能__辅助驾驶系统());
            autoBean.set_C_易车_C_驾驶功能__辅助驾驶等级(((Bean_Two) yiCheData).get_C_易车_C_驾驶功能__辅助驾驶等级());
            autoBean.set_C_易车_C_驾驶功能__道路交通标识识别(((Bean_Two) yiCheData).get_C_易车_C_驾驶功能__道路交通标识识别());
            autoBean.set_C_易车_C_驾驶功能__车道居中保持(((Bean_Two) yiCheData).get_C_易车_C_驾驶功能__车道居中保持());
            autoBean.set_C_易车_C_驾驶功能__车道保持辅助系统(((Bean_Two) yiCheData).get_C_易车_C_驾驶功能__车道保持辅助系统());
            autoBean.set_C_易车_C_驾驶功能__并线辅助(((Bean_Two) yiCheData).get_C_易车_C_驾驶功能__并线辅助());
            autoBean.set_C_易车_C_驾驶功能__AR实景导航(((Bean_Two) yiCheData).get_C_易车_C_驾驶功能__AR实景导航());
            autoBean.set_C_易车_C_驾驶操控__自动驻车(((Bean_Two) yiCheData).get_C_易车_C_驾驶操控__自动驻车());
            autoBean.set_C_易车_C_驾驶操控__整体主动转向系统(((Bean_Two) yiCheData).get_C_易车_C_驾驶操控__整体主动转向系统());
            autoBean.set_C_易车_C_驾驶操控__上坡辅助(((Bean_Two) yiCheData).get_C_易车_C_驾驶操控__上坡辅助());
            autoBean.set_C_易车_C_驾驶操控__可变转向比(((Bean_Two) yiCheData).get_C_易车_C_驾驶操控__可变转向比());
            autoBean.set_C_易车_C_驾驶操控__可变悬架功能(((Bean_Two) yiCheData).get_C_易车_C_驾驶操控__可变悬架功能());
            autoBean.set_C_易车_C_驾驶操控__驾驶模式切换(((Bean_Two) yiCheData).get_C_易车_C_驾驶操控__驾驶模式切换());
            autoBean.set_C_易车_C_驾驶操控__发动机启停技术(((Bean_Two) yiCheData).get_C_易车_C_驾驶操控__发动机启停技术());
            autoBean.set_C_易车_C_驾驶操控__陡坡缓降(((Bean_Two) yiCheData).get_C_易车_C_驾驶操控__陡坡缓降());
            autoBean.set_C_易车_C_驾驶操控__单踏板模式(((Bean_Two) yiCheData).get_C_易车_C_驾驶操控__单踏板模式());
            autoBean.set_C_易车_C_基本参数__最高车速_km_h(((Bean_Two) yiCheData).get_C_易车_C_基本参数__最高车速_km_h());
            autoBean.set_C_易车_C_基本参数__整车质保(((Bean_Two) yiCheData).get_C_易车_C_基本参数__整车质保());
            autoBean.set_C_易车_C_基本参数__长_宽_高_mm(((Bean_Two) yiCheData).get_C_易车_C_基本参数__长_宽_高_mm());
            autoBean.set_C_易车_C_基本参数__首任车主质保政策(((Bean_Two) yiCheData).get_C_易车_C_基本参数__首任车主质保政策());
            autoBean.set_C_易车_C_基本参数__上市时间(((Bean_Two) yiCheData).get_C_易车_C_基本参数__上市时间());
            autoBean.set_C_易车_C_基本参数__能源类型(((Bean_Two) yiCheData).get_C_易车_C_基本参数__能源类型());
            autoBean.set_C_易车_C_基本参数__级别(((Bean_Two) yiCheData).get_C_易车_C_基本参数__级别());
            autoBean.set_C_易车_C_基本参数__环保标准(((Bean_Two) yiCheData).get_C_易车_C_基本参数__环保标准());
            autoBean.set_C_易车_C_基本参数__官方0_100km_h加速_s(((Bean_Two) yiCheData).get_C_易车_C_基本参数__官方0_100km_h加速_s());
            autoBean.set_C_易车_C_基本参数__发动机(((Bean_Two) yiCheData).get_C_易车_C_基本参数__发动机());
            autoBean.set_C_易车_C_基本参数__电动机_Ps(((Bean_Two) yiCheData).get_C_易车_C_基本参数__电动机_Ps());
            autoBean.set_C_易车_C_基本参数__电池慢充时间_小时(((Bean_Two) yiCheData).get_C_易车_C_基本参数__电池慢充时间_小时());
            autoBean.set_C_易车_C_基本参数__电池慢充电量范围(((Bean_Two) yiCheData).get_C_易车_C_基本参数__电池慢充电量范围());
            autoBean.set_C_易车_C_基本参数__电池快充时间_小时(((Bean_Two) yiCheData).get_C_易车_C_基本参数__电池快充时间_小时());
            autoBean.set_C_易车_C_基本参数__电池快充电量范围(((Bean_Two) yiCheData).get_C_易车_C_基本参数__电池快充电量范围());
            autoBean.set_C_易车_C_基本参数__车型名称(((Bean_Two) yiCheData).get_C_易车_C_基本参数__车型名称());
            autoBean.set_C_易车_C_基本参数__车身结构(((Bean_Two) yiCheData).get_C_易车_C_基本参数__车身结构());
            autoBean.set_C_易车_C_基本参数__厂商指导价_元(((Bean_Two) yiCheData).get_C_易车_C_基本参数__厂商指导价_元());
            autoBean.set_C_易车_C_基本参数__厂商(((Bean_Two) yiCheData).get_C_易车_C_基本参数__厂商());
            autoBean.set_C_易车_C_基本参数__变速箱(((Bean_Two) yiCheData).get_C_易车_C_基本参数__变速箱());
            autoBean.set_C_易车_C_基本参数__WLTC综合油耗_L_100km(((Bean_Two) yiCheData).get_C_易车_C_基本参数__WLTC综合油耗_L_100km());
            autoBean.set_C_易车_C_基本参数__WLTC纯电续航里程_km(((Bean_Two) yiCheData).get_C_易车_C_基本参数__WLTC纯电续航里程_km());
            autoBean.set_C_易车_C_基本参数__NEDC综合油耗_L_100km(((Bean_Two) yiCheData).get_C_易车_C_基本参数__NEDC综合油耗_L_100km());
            autoBean.set_C_易车_C_基本参数__NEDC纯电续航里程_km(((Bean_Two) yiCheData).get_C_易车_C_基本参数__NEDC纯电续航里程_km());
            autoBean.set_C_易车_C_基本参数__EPA纯电续航里程_km(((Bean_Two) yiCheData).get_C_易车_C_基本参数__EPA纯电续航里程_km());
            autoBean.set_C_易车_C_基本参数__CLTC纯电续航里程_km(((Bean_Two) yiCheData).get_C_易车_C_基本参数__CLTC纯电续航里程_km());
            autoBean.set_C_易车_C_方向盘_内后视镜__仪表盘屏幕像素密度(((Bean_Two) yiCheData).get_C_易车_C_方向盘_内后视镜__仪表盘屏幕像素密度());
            autoBean.set_C_易车_C_方向盘_内后视镜__仪表盘屏幕分辨率_px(((Bean_Two) yiCheData).get_C_易车_C_方向盘_内后视镜__仪表盘屏幕分辨率_px());
            autoBean.set_C_易车_C_方向盘_内后视镜__仪表盘屏幕材质(((Bean_Two) yiCheData).get_C_易车_C_方向盘_内后视镜__仪表盘屏幕材质());
            autoBean.set_C_易车_C_方向盘_内后视镜__液晶仪表尺寸(((Bean_Two) yiCheData).get_C_易车_C_方向盘_内后视镜__液晶仪表尺寸());
            autoBean.set_C_易车_C_方向盘_内后视镜__全液晶仪表盘(((Bean_Two) yiCheData).get_C_易车_C_方向盘_内后视镜__全液晶仪表盘());
            autoBean.set_C_易车_C_方向盘_内后视镜__换挡形式(((Bean_Two) yiCheData).get_C_易车_C_方向盘_内后视镜__换挡形式());
            autoBean.set_C_易车_C_方向盘_内后视镜__行车电脑显示屏幕(((Bean_Two) yiCheData).get_C_易车_C_方向盘_内后视镜__行车电脑显示屏幕());
            autoBean.set_C_易车_C_方向盘_内后视镜__方向盘位置调节(((Bean_Two) yiCheData).get_C_易车_C_方向盘_内后视镜__方向盘位置调节());
            autoBean.set_C_易车_C_方向盘_内后视镜__方向盘加热(((Bean_Two) yiCheData).get_C_易车_C_方向盘_内后视镜__方向盘加热());
            autoBean.set_C_易车_C_方向盘_内后视镜__方向盘换挡(((Bean_Two) yiCheData).get_C_易车_C_方向盘_内后视镜__方向盘换挡());
            autoBean.set_C_易车_C_方向盘_内后视镜__方向盘材质(((Bean_Two) yiCheData).get_C_易车_C_方向盘_内后视镜__方向盘材质());
            autoBean.set_C_易车_C_方向盘_内后视镜__多功能方向盘(((Bean_Two) yiCheData).get_C_易车_C_方向盘_内后视镜__多功能方向盘());
            autoBean.set_C_易车_C_方向盘_内后视镜__HUD抬头数字显示(((Bean_Two) yiCheData).get_C_易车_C_方向盘_内后视镜__HUD抬头数字显示());
            autoBean.set_C_易车_C_方向盘_内后视镜__ETC装置(((Bean_Two) yiCheData).get_C_易车_C_方向盘_内后视镜__ETC装置());
            autoBean.set_C_易车_C_发动机__最大扭矩转速_rpm(((Bean_Two) yiCheData).get_C_易车_C_发动机__最大扭矩转速_rpm());
            autoBean.set_C_易车_C_发动机__最大扭矩_N_m(((Bean_Two) yiCheData).get_C_易车_C_发动机__最大扭矩_N_m());
            autoBean.set_C_易车_C_发动机__最大马力_Ps(((Bean_Two) yiCheData).get_C_易车_C_发动机__最大马力_Ps());
            autoBean.set_C_易车_C_发动机__最大净功率_kW(((Bean_Two) yiCheData).get_C_易车_C_发动机__最大净功率_kW());
            autoBean.set_C_易车_C_发动机__最大功率转速_rpm(((Bean_Two) yiCheData).get_C_易车_C_发动机__最大功率转速_rpm());
            autoBean.set_C_易车_C_发动机__最大功率_kW(((Bean_Two) yiCheData).get_C_易车_C_发动机__最大功率_kW());
            autoBean.set_C_易车_C_发动机__压缩比(((Bean_Two) yiCheData).get_C_易车_C_发动机__压缩比());
            autoBean.set_C_易车_C_发动机__推荐燃油标号(((Bean_Two) yiCheData).get_C_易车_C_发动机__推荐燃油标号());
            autoBean.set_C_易车_C_发动机__气缸数_个(((Bean_Two) yiCheData).get_C_易车_C_发动机__气缸数_个());
            autoBean.set_C_易车_C_发动机__气缸排列形式(((Bean_Two) yiCheData).get_C_易车_C_发动机__气缸排列形式());
            autoBean.set_C_易车_C_发动机__配气机构(((Bean_Two) yiCheData).get_C_易车_C_发动机__配气机构());
            autoBean.set_C_易车_C_发动机__排量_mL(((Bean_Two) yiCheData).get_C_易车_C_发动机__排量_mL());
            autoBean.set_C_易车_C_发动机__排量_L(((Bean_Two) yiCheData).get_C_易车_C_发动机__排量_L());
            autoBean.set_C_易车_C_发动机__每缸气门数_个(((Bean_Two) yiCheData).get_C_易车_C_发动机__每缸气门数_个());
            autoBean.set_C_易车_C_发动机__进气形式(((Bean_Two) yiCheData).get_C_易车_C_发动机__进气形式());
            autoBean.set_C_易车_C_发动机__环保标准(((Bean_Two) yiCheData).get_C_易车_C_发动机__环保标准());
            autoBean.set_C_易车_C_发动机__供油方式(((Bean_Two) yiCheData).get_C_易车_C_发动机__供油方式());
            autoBean.set_C_易车_C_发动机__缸体材料(((Bean_Two) yiCheData).get_C_易车_C_发动机__缸体材料());
            autoBean.set_C_易车_C_发动机__缸盖材料(((Bean_Two) yiCheData).get_C_易车_C_发动机__缸盖材料());
            autoBean.set_C_易车_C_发动机__发动机型号(((Bean_Two) yiCheData).get_C_易车_C_发动机__发动机型号());
            autoBean.set_C_易车_C_发动机__发动机布局(((Bean_Two) yiCheData).get_C_易车_C_发动机__发动机布局());
            autoBean.set_C_易车_C_电动机__系统综合扭矩_N_m(((Bean_Two) yiCheData).get_C_易车_C_电动机__系统综合扭矩_N_m());
            autoBean.set_C_易车_C_电动机__系统综合功率_Ps(((Bean_Two) yiCheData).get_C_易车_C_电动机__系统综合功率_Ps());
            autoBean.set_C_易车_C_电动机__系统综合功率_kW(((Bean_Two) yiCheData).get_C_易车_C_电动机__系统综合功率_kW());
            autoBean.set_C_易车_C_电动机__驱动电机数(((Bean_Two) yiCheData).get_C_易车_C_电动机__驱动电机数());
            autoBean.set_C_易车_C_电动机__前电动机最大扭矩_N_m(((Bean_Two) yiCheData).get_C_易车_C_电动机__前电动机最大扭矩_N_m());
            autoBean.set_C_易车_C_电动机__前电动机最大功率_kW(((Bean_Two) yiCheData).get_C_易车_C_电动机__前电动机最大功率_kW());
            autoBean.set_C_易车_C_电动机__慢充接口位置(((Bean_Two) yiCheData).get_C_易车_C_电动机__慢充接口位置());
            autoBean.set_C_易车_C_电动机__快充接口位置(((Bean_Two) yiCheData).get_C_易车_C_电动机__快充接口位置());
            autoBean.set_C_易车_C_电动机__快充功率_kW(((Bean_Two) yiCheData).get_C_易车_C_电动机__快充功率_kW());
            autoBean.set_C_易车_C_电动机__换电(((Bean_Two) yiCheData).get_C_易车_C_电动机__换电());
            autoBean.set_C_易车_C_电动机__后电动机最大扭矩_N_m(((Bean_Two) yiCheData).get_C_易车_C_电动机__后电动机最大扭矩_N_m());
            autoBean.set_C_易车_C_电动机__后电动机最大功率_kW(((Bean_Two) yiCheData).get_C_易车_C_电动机__后电动机最大功率_kW());
            autoBean.set_C_易车_C_电动机__电芯品牌(((Bean_Two) yiCheData).get_C_易车_C_电动机__电芯品牌());
            autoBean.set_C_易车_C_电动机__电机类型(((Bean_Two) yiCheData).get_C_易车_C_电动机__电机类型());
            autoBean.set_C_易车_C_电动机__电机布局(((Bean_Two) yiCheData).get_C_易车_C_电动机__电机布局());
            autoBean.set_C_易车_C_电动机__电动机总扭矩_N_m(((Bean_Two) yiCheData).get_C_易车_C_电动机__电动机总扭矩_N_m());
            autoBean.set_C_易车_C_电动机__电动机总马力_Ps(((Bean_Two) yiCheData).get_C_易车_C_电动机__电动机总马力_Ps());
            autoBean.set_C_易车_C_电动机__电动机总功率_kW(((Bean_Two) yiCheData).get_C_易车_C_电动机__电动机总功率_kW());
            autoBean.set_C_易车_C_电动机__电池组质保(((Bean_Two) yiCheData).get_C_易车_C_电动机__电池组质保());
            autoBean.set_C_易车_C_电动机__电池能量密度_Wh_kg(((Bean_Two) yiCheData).get_C_易车_C_电动机__电池能量密度_Wh_kg());
            autoBean.set_C_易车_C_电动机__电池能量_kWh(((Bean_Two) yiCheData).get_C_易车_C_电动机__电池能量_kWh());
            autoBean.set_C_易车_C_电动机__电池慢充时间_小时(((Bean_Two) yiCheData).get_C_易车_C_电动机__电池慢充时间_小时());
            autoBean.set_C_易车_C_电动机__电池慢充电量范围(((Bean_Two) yiCheData).get_C_易车_C_电动机__电池慢充电量范围());
            autoBean.set_C_易车_C_电动机__电池类型(((Bean_Two) yiCheData).get_C_易车_C_电动机__电池类型());
            autoBean.set_C_易车_C_电动机__电池快充时间_小时(((Bean_Two) yiCheData).get_C_易车_C_电动机__电池快充时间_小时());
            autoBean.set_C_易车_C_电动机__电池快充电量范围(((Bean_Two) yiCheData).get_C_易车_C_电动机__电池快充电量范围());
            autoBean.set_C_易车_C_电动机__百公里耗电量_kWh_100km(((Bean_Two) yiCheData).get_C_易车_C_电动机__百公里耗电量_kWh_100km());
            autoBean.set_C_易车_C_电动机__WLTP纯电续航里程_km(((Bean_Two) yiCheData).get_C_易车_C_电动机__WLTP纯电续航里程_km());
            autoBean.set_C_易车_C_电动机__WLTC综合续航_km(((Bean_Two) yiCheData).get_C_易车_C_电动机__WLTC综合续航_km());
            autoBean.set_C_易车_C_电动机__NEDC综合续航_km(((Bean_Two) yiCheData).get_C_易车_C_电动机__NEDC综合续航_km());
            autoBean.set_C_易车_C_电动机__NEDC纯电续航里程_km(((Bean_Two) yiCheData).get_C_易车_C_电动机__NEDC纯电续航里程_km());
            autoBean.set_C_易车_C_电动机__EPA纯电续航里程_km(((Bean_Two) yiCheData).get_C_易车_C_电动机__EPA纯电续航里程_km());
            autoBean.set_C_易车_C_电动机__CLTC综合续航_km(((Bean_Two) yiCheData).get_C_易车_C_电动机__CLTC综合续航_km());
            autoBean.set_C_易车_C_电动机__CLTC纯电续航里程_km(((Bean_Two) yiCheData).get_C_易车_C_电动机__CLTC纯电续航里程_km());
            autoBean.set_C_易车_C_底盘转向__助力类型(((Bean_Two) yiCheData).get_C_易车_C_底盘转向__助力类型());
            autoBean.set_C_易车_C_底盘转向__中央差速器结构(((Bean_Two) yiCheData).get_C_易车_C_底盘转向__中央差速器结构());
            autoBean.set_C_易车_C_底盘转向__四驱形式(((Bean_Two) yiCheData).get_C_易车_C_底盘转向__四驱形式());
            autoBean.set_C_易车_C_底盘转向__驱动方式(((Bean_Two) yiCheData).get_C_易车_C_底盘转向__驱动方式());
            autoBean.set_C_易车_C_底盘转向__前悬架类型(((Bean_Two) yiCheData).get_C_易车_C_底盘转向__前悬架类型());
            autoBean.set_C_易车_C_底盘转向__后悬架类型(((Bean_Two) yiCheData).get_C_易车_C_底盘转向__后悬架类型());
            autoBean.set_C_易车_C_底盘转向__车体结构(((Bean_Two) yiCheData).get_C_易车_C_底盘转向__车体结构());
            autoBean.set_C_易车_C_车外灯光__转向辅助灯(((Bean_Two) yiCheData).get_C_易车_C_车外灯光__转向辅助灯());
            autoBean.set_C_易车_C_车外灯光__远光灯光源(((Bean_Two) yiCheData).get_C_易车_C_车外灯光__远光灯光源());
            autoBean.set_C_易车_C_车外灯光__近光灯光源(((Bean_Two) yiCheData).get_C_易车_C_车外灯光__近光灯光源());
            autoBean.set_C_易车_C_车外灯光__灯光特色功能(((Bean_Two) yiCheData).get_C_易车_C_车外灯光__灯光特色功能());
            autoBean.set_C_易车_C_车外灯光__大灯清洗装置(((Bean_Two) yiCheData).get_C_易车_C_车外灯光__大灯清洗装置());
            autoBean.set_C_易车_C_车外灯光__车前雾灯(((Bean_Two) yiCheData).get_C_易车_C_车外灯光__车前雾灯());
            autoBean.set_C_易车_C_车外灯光__LED日间行车灯(((Bean_Two) yiCheData).get_C_易车_C_车外灯光__LED日间行车灯());
            autoBean.set_C_易车_C_车身__座位数_个(((Bean_Two) yiCheData).get_C_易车_C_车身__座位数_个());
            autoBean.set_C_易车_C_车身__最小转弯半径_m(((Bean_Two) yiCheData).get_C_易车_C_车身__最小转弯半径_m());
            autoBean.set_C_易车_C_车身__最大载重质量_kg(((Bean_Two) yiCheData).get_C_易车_C_车身__最大载重质量_kg());
            autoBean.set_C_易车_C_车身__最大涉水深度_mm(((Bean_Two) yiCheData).get_C_易车_C_车身__最大涉水深度_mm());
            autoBean.set_C_易车_C_车身__最大爬坡度(((Bean_Two) yiCheData).get_C_易车_C_车身__最大爬坡度());
            autoBean.set_C_易车_C_车身__轴距_mm(((Bean_Two) yiCheData).get_C_易车_C_车身__轴距_mm());
            autoBean.set_C_易车_C_车身__长度_mm(((Bean_Two) yiCheData).get_C_易车_C_车身__长度_mm());
            autoBean.set_C_易车_C_车身__油箱容积_L(((Bean_Two) yiCheData).get_C_易车_C_车身__油箱容积_L());
            autoBean.set_C_易车_C_车身__前轮距_mm(((Bean_Two) yiCheData).get_C_易车_C_车身__前轮距_mm());
            autoBean.set_C_易车_C_车身__前备厢容积_L(((Bean_Two) yiCheData).get_C_易车_C_车身__前备厢容积_L());
            autoBean.set_C_易车_C_车身__气罐容积_L(((Bean_Two) yiCheData).get_C_易车_C_车身__气罐容积_L());
            autoBean.set_C_易车_C_车身__满载最小离地间隙_mm(((Bean_Two) yiCheData).get_C_易车_C_车身__满载最小离地间隙_mm());
            autoBean.set_C_易车_C_车身__离去角(((Bean_Two) yiCheData).get_C_易车_C_车身__离去角());
            autoBean.set_C_易车_C_车身__宽度_mm(((Bean_Two) yiCheData).get_C_易车_C_车身__宽度_mm());
            autoBean.set_C_易车_C_车身__空载最小离地间隙_mm(((Bean_Two) yiCheData).get_C_易车_C_车身__空载最小离地间隙_mm());
            autoBean.set_C_易车_C_车身__接近角(((Bean_Two) yiCheData).get_C_易车_C_车身__接近角());
            autoBean.set_C_易车_C_车身__货箱尺寸_mm(((Bean_Two) yiCheData).get_C_易车_C_车身__货箱尺寸_mm());
            autoBean.set_C_易车_C_车身__后轮距_mm(((Bean_Two) yiCheData).get_C_易车_C_车身__后轮距_mm());
            autoBean.set_C_易车_C_车身__后备厢容积_L(((Bean_Two) yiCheData).get_C_易车_C_车身__后备厢容积_L());
            autoBean.set_C_易车_C_车身__高度_mm(((Bean_Two) yiCheData).get_C_易车_C_车身__高度_mm());
            autoBean.set_C_易车_C_车身__风阻系数_Cd(((Bean_Two) yiCheData).get_C_易车_C_车身__风阻系数_Cd());
            autoBean.set_C_易车_C_车身__车门数_个(((Bean_Two) yiCheData).get_C_易车_C_车身__车门数_个());
            autoBean.set_C_易车_C_车身__车门开启方式(((Bean_Two) yiCheData).get_C_易车_C_车身__车门开启方式());
            autoBean.set_C_易车_C_车内充电__手机无线充电功能(((Bean_Two) yiCheData).get_C_易车_C_车内充电__手机无线充电功能());
            autoBean.set_C_易车_C_车内充电__行李厢12V电源接口(((Bean_Two) yiCheData).get_C_易车_C_车内充电__行李厢12V电源接口());
            autoBean.set_C_易车_C_车内充电__多媒体_充电接口(((Bean_Two) yiCheData).get_C_易车_C_车内充电__多媒体_充电接口());
            autoBean.set_C_易车_C_车内充电__USB_Type_C接口数量(((Bean_Two) yiCheData).get_C_易车_C_车内充电__USB_Type_C接口数量());
            autoBean.set_C_易车_C_车内充电__220V_230V电源(((Bean_Two) yiCheData).get_C_易车_C_车内充电__220V_230V电源());
            autoBean.set_C_易车_C_车轮制动__驻车制动类型(((Bean_Two) yiCheData).get_C_易车_C_车轮制动__驻车制动类型());
            autoBean.set_C_易车_C_车轮制动__前制动器类型(((Bean_Two) yiCheData).get_C_易车_C_车轮制动__前制动器类型());
            autoBean.set_C_易车_C_车轮制动__前轮胎规格(((Bean_Two) yiCheData).get_C_易车_C_车轮制动__前轮胎规格());
            autoBean.set_C_易车_C_车轮制动__后制动器类型(((Bean_Two) yiCheData).get_C_易车_C_车轮制动__后制动器类型());
            autoBean.set_C_易车_C_车轮制动__后轮胎规格(((Bean_Two) yiCheData).get_C_易车_C_车轮制动__后轮胎规格());
            autoBean.set_C_易车_C_车轮制动__备胎规格(((Bean_Two) yiCheData).get_C_易车_C_车轮制动__备胎规格());
            autoBean.set_C_易车_C_车轮制动__备胎放置方式(((Bean_Two) yiCheData).get_C_易车_C_车轮制动__备胎放置方式());
            autoBean.set_C_易车_C_被动安全__主_副驾驶座安全气囊(((Bean_Two) yiCheData).get_C_易车_C_被动安全__主_副驾驶座安全气囊());
            autoBean.set_C_易车_C_被动安全__膝部气囊(((Bean_Two) yiCheData).get_C_易车_C_被动安全__膝部气囊());
            autoBean.set_C_易车_C_被动安全__缺气保用轮胎(((Bean_Two) yiCheData).get_C_易车_C_被动安全__缺气保用轮胎());
            autoBean.set_C_易车_C_被动安全__前_后排侧气囊(((Bean_Two) yiCheData).get_C_易车_C_被动安全__前_后排侧气囊());
            autoBean.set_C_易车_C_被动安全__后排座椅防下滑气囊(((Bean_Two) yiCheData).get_C_易车_C_被动安全__后排座椅防下滑气囊());
            autoBean.set_C_易车_C_被动安全__后排安全带式气囊(((Bean_Two) yiCheData).get_C_易车_C_被动安全__后排安全带式气囊());
            autoBean.set_C_易车_C_被动安全__副驾驶座垫式气囊(((Bean_Two) yiCheData).get_C_易车_C_被动安全__副驾驶座垫式气囊());
            autoBean.set_C_易车_C_被动安全__被动行人保护(((Bean_Two) yiCheData).get_C_易车_C_被动安全__被动行人保护());
            dataList.add(autoBean);
        }
        System.out.println(dataList.size());
        insertCompare.insert_除匹配的数据(dataList);


    }

    public void method_之后再处理() {
        // 读取匹配结果txt
        ArrayList<String> contentList = T_Config_File.method_按行读取文件("/Users/asteroid/所有文件数据/对比结果/匹配结果备份12.txt");
        for (String rowValue : contentList) {
//            System.out.println(rowValue);
            String[] rowValueList = rowValue.split("\t");
            for (int i = 0; i < rowValueList.length; i++) {
                String ids = rowValueList[0];
                String qczjId = rowValueList[1];
                String yiCheId = rowValueList[2];
                String qczjName = rowValueList[3];
                String yiCheName = rowValueList[4];
                if (rowValueList.length > 5) {// 有不同配置的数据
                    String noSameConfig = rowValueList[5];
                    if (qczjName.equals(yiCheName.replace(" ", "").trim())) {
                        if (!noSameConfig.equals("")) {
                            String[] valuesList = noSameConfig.split("\\|\\|");
                            for (int j = 0; j < valuesList.length; j++) {
                                String columnName = valuesList[j].substring(0, valuesList[j].indexOf("=>"));
                                String[] values = valuesList[j].substring(valuesList[j].indexOf("=>") + 2).split("->");
                                String qczjValue = values[0];
                                String yiCheValue = "";
                                if (values.length > 1) {
                                    yiCheValue = values[1];
                                }
                                System.out.println("1\t" + qczjValue + "\t" + yiCheValue);
                            }
                        }
                    } else {
                        if (!noSameConfig.equals("")) {
                            String[] valuesList = noSameConfig.split("\\|\\|");
                            for (int j = 0; j < valuesList.length; j++) {
                                System.out.println(valuesList[j]);
                                String columnName = valuesList[j].substring(0, valuesList[j].indexOf("=>"));
                                String[] values = valuesList[j].substring(valuesList[j].indexOf("=>") + 2).split("->");
                                String qczjValue = values[0];
                                String yiCheValue = "";
                                if (values.length > 1) {
                                    yiCheValue = values[1];
                                }
                                System.out.println("2\t" + qczjValue + "\t" + yiCheValue);
                            }
                        }
                    }
                }

            }
        }
    }


}
