package com.wangtiantian.entity.ershouche.yiChe;

public class YiChe_CarInfo {
    private String  C_tradeNumber; public void set_C_tradeNumber(String C_tradeNumber){this.C_tradeNumber=C_tradeNumber.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_tradeNumber(){return C_tradeNumber;}
    private String  C_carName; public void set_C_carName(String C_carName){this.C_carName=C_carName.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_carName(){return C_carName;}
    private String  C_platformAuth; public void set_C_platformAuth(String C_platformAuth){this.C_platformAuth=C_platformAuth.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_platformAuth(){return C_platformAuth;}
    private String  C_vendorId; public void set_C_vendorId(String C_vendorId){this.C_vendorId=C_vendorId.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_vendorId(){return C_vendorId;}
    private String  C_cityId; public void set_C_cityId(String C_cityId){this.C_cityId=C_cityId.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_cityId(){return C_cityId;}
    private String  C_source; public void set_C_source(String C_source){this.C_source=C_source.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_source(){return C_source;}
    private String  C_licenseDate; public void set_C_licenseDate(String C_licenseDate){this.C_licenseDate=C_licenseDate.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_licenseDate(){return C_licenseDate;}
    private String  C_carYear; public void set_C_carYear(String C_carYear){this.C_carYear=C_carYear.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_carYear(){return C_carYear;}
    private String  C_unifiedDistributionNumber; public void set_C_unifiedDistributionNumber(String C_unifiedDistributionNumber){this.C_unifiedDistributionNumber=C_unifiedDistributionNumber.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_unifiedDistributionNumber(){return C_unifiedDistributionNumber;}
    private String  C_referPrice; public void set_C_referPrice(String C_referPrice){this.C_referPrice=C_referPrice.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_referPrice(){return C_referPrice;}
    private String  C_videoCount; public void set_C_videoCount(String C_videoCount){this.C_videoCount=C_videoCount.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_videoCount(){return C_videoCount;}
    private String  C_serialName; public void set_C_serialName(String C_serialName){this.C_serialName=C_serialName.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_serialName(){return C_serialName;}
    private String  C_extUCarId; public void set_C_extUCarId(String C_extUCarId){this.C_extUCarId=C_extUCarId.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_extUCarId(){return C_extUCarId;}
    private String  C_usedId; public void set_C_usedId(String C_usedId){this.C_usedId=C_usedId.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_usedId(){return C_usedId;}
    private String  C_cityLocalName; public void set_C_cityLocalName(String C_cityLocalName){this.C_cityLocalName=C_cityLocalName.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_cityLocalName(){return C_cityLocalName;}
    private String  C_carType; public void set_C_carType(String C_carType){this.C_carType=C_carType.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_carType(){return C_carType;}
    private String  C_cityName; public void set_C_cityName(String C_cityName){this.C_cityName=C_cityName.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_cityName(){return C_cityName;}
    private String  C_serialId; public void set_C_serialId(String C_serialId){this.C_serialId=C_serialId.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_serialId(){return C_serialId;}
    private String  C_displayPrice; public void set_C_displayPrice(String C_displayPrice){this.C_displayPrice=C_displayPrice.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_displayPrice(){return C_displayPrice;}
    private String  C_monthlyPayment; public void set_C_monthlyPayment(String C_monthlyPayment){this.C_monthlyPayment=C_monthlyPayment.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_monthlyPayment(){return C_monthlyPayment;}
    private String  C_downPayment; public void set_C_downPayment(String C_downPayment){this.C_downPayment=C_downPayment.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_downPayment(){return C_downPayment;}
    private String  C_ypUsedId; public void set_C_ypUsedId(String C_ypUsedId){this.C_ypUsedId=C_ypUsedId.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_ypUsedId(){return C_ypUsedId;}
    private String  C_isFixedPrice; public void set_C_isFixedPrice(String C_isFixedPrice){this.C_isFixedPrice=C_isFixedPrice.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_isFixedPrice(){return C_isFixedPrice;}
    private String  C_uCarId; public void set_C_uCarId(String C_uCarId){this.C_uCarId=C_uCarId.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_uCarId(){return C_uCarId;}
    private String  C_cityStandardId; public void set_C_cityStandardId(String C_cityStandardId){this.C_cityStandardId=C_cityStandardId.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_cityStandardId(){return C_cityStandardId;}
    private String  C_unifiedNumber; public void set_C_unifiedNumber(String C_unifiedNumber){this.C_unifiedNumber=C_unifiedNumber.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_unifiedNumber(){return C_unifiedNumber;}
    private String  C_isParallelImportCar; public void set_C_isParallelImportCar(String C_isParallelImportCar){this.C_isParallelImportCar=C_isParallelImportCar.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_isParallelImportCar(){return C_isParallelImportCar;}
    private String  C_relationIndex; public void set_C_relationIndex(String C_relationIndex){this.C_relationIndex=C_relationIndex.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_relationIndex(){return C_relationIndex;}
    private String  C_vendorName; public void set_C_vendorName(String C_vendorName){this.C_vendorName=C_vendorName.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_vendorName(){return C_vendorName;}
    private String  C_keyAccountLabel; public void set_C_keyAccountLabel(String C_keyAccountLabel){this.C_keyAccountLabel=C_keyAccountLabel.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_keyAccountLabel(){return C_keyAccountLabel;}
    private String  C_carId; public void set_C_carId(String C_carId){this.C_carId=C_carId.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_carId(){return C_carId;}
    private String  C_coverUrl; public void set_C_coverUrl(String C_coverUrl){this.C_coverUrl=C_coverUrl.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_coverUrl(){return C_coverUrl;}
    private String  C_drivingMileage; public void set_C_drivingMileage(String C_drivingMileage){this.C_drivingMileage=C_drivingMileage.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_drivingMileage(){return C_drivingMileage;}
    private String  C_recommendType; public void set_C_recommendType(String C_recommendType){this.C_recommendType=C_recommendType.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_recommendType(){return C_recommendType;}
    private String  C_unifiedVendorNumber; public void set_C_unifiedVendorNumber(String C_unifiedVendorNumber){this.C_unifiedVendorNumber=C_unifiedVendorNumber.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_unifiedVendorNumber(){return C_unifiedVendorNumber;}
    private String  C_relationPage; public void set_C_relationPage(String C_relationPage){this.C_relationPage=C_relationPage.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_relationPage(){return C_relationPage;}
    private int  C_ID;public int  get_C_ID(){return C_ID;}public void set_C_ID(int C_ID){this.C_ID=C_ID;}
    private String  C_UpdateTime;public String  get_C_UpdateTime(){return C_UpdateTime;}public void set_C_UpdateTime(String C_UpdateTime){this.C_UpdateTime=C_UpdateTime==null?"-":C_UpdateTime.replace("\t","").replace("\r","").replace("\r\n","").replace("\n","");}
    private String  C_bgcolor; public void set_C_bgcolor(String C_bgcolor){this.C_bgcolor=C_bgcolor.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_bgcolor(){return C_bgcolor;}
    private String  C_labelText; public void set_C_labelText(String C_labelText){this.C_labelText=C_labelText.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_labelText(){return C_labelText;}
    private String  C_fontText; public void set_C_fontText(String C_fontText){this.C_fontText=C_fontText.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_fontText(){return C_fontText;}
    private String  C_type; public void set_C_type(String C_type){this.C_type=C_type.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_type(){return C_type;}
    private String  C_colorType; public void set_C_colorType(String C_colorType){this.C_colorType=C_colorType.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_colorType(){return C_colorType;}
    private String  C_FileName; public void set_C_FileName(String C_FileName){this.C_FileName=C_FileName.replace("\n","").replace("\r","").replace("\t","").replace("'","''").trim();}public String get_C_FileName(){return C_FileName;}
    private int  C_IsFinish;public int  get_C_IsFinish(){return C_IsFinish;}public void set_C_IsFinish(int C_IsFinish){this.C_IsFinish=C_IsFinish;}
}
