package com.wangtiantian.entity.ershouche.che300;

public class Che300_CityData {
    private int  C_ID;public int  get_C_ID(){return C_ID;}public void set_C_ID(int C_ID){this.C_ID=C_ID;}
    private String  C_prov_admin_code;public String  get_C_prov_admin_code(){return C_prov_admin_code;}public void set_C_prov_admin_code(String C_prov_admin_code){this.C_prov_admin_code=C_prov_admin_code==null?"-":C_prov_admin_code.replace("\t","").replace("\r","").replace("\r\n","").replace("\n","");}
    private String  C_prov_id;public String  get_C_prov_id(){return C_prov_id;}public void set_C_prov_id(String C_prov_id){this.C_prov_id=C_prov_id==null?"-":C_prov_id.replace("\t","").replace("\r","").replace("\r\n","").replace("\n","");}
    private String  C_prov_name;public String  get_C_prov_name(){return C_prov_name;}public void set_C_prov_name(String C_prov_name){this.C_prov_name=C_prov_name==null?"-":C_prov_name.replace("\t","").replace("\r","").replace("\r\n","").replace("\n","");}
    private String  C_pro_initial;public String  get_C_pro_initial(){return C_pro_initial;}public void set_C_pro_initial(String C_pro_initial){this.C_pro_initial=C_pro_initial==null?"-":C_pro_initial.replace("\t","").replace("\r","").replace("\r\n","").replace("\n","");}
    private String  C_lot;public String  get_C_lot(){return C_lot;}public void set_C_lot(String C_lot){this.C_lot=C_lot==null?"-":C_lot.replace("\t","").replace("\r","").replace("\r\n","").replace("\n","");}
    private String  C_admin_code;public String  get_C_admin_code(){return C_admin_code;}public void set_C_admin_code(String C_admin_code){this.C_admin_code=C_admin_code==null?"-":C_admin_code.replace("\t","").replace("\r","").replace("\r\n","").replace("\n","");}
    private String  C_city_name;public String  get_C_city_name(){return C_city_name;}public void set_C_city_name(String C_city_name){this.C_city_name=C_city_name==null?"-":C_city_name.replace("\t","").replace("\r","").replace("\r\n","").replace("\n","");}
    private String  C_all_plate_prefix;public String  get_C_all_plate_prefix(){return C_all_plate_prefix;}public void set_C_all_plate_prefix(String C_all_plate_prefix){this.C_all_plate_prefix=C_all_plate_prefix==null?"-":C_all_plate_prefix.replace("\t","").replace("\r","").replace("\r\n","").replace("\n","");}
    private String  C_city_initial;public String  get_C_city_initial(){return C_city_initial;}public void set_C_city_initial(String C_city_initial){this.C_city_initial=C_city_initial==null?"-":C_city_initial.replace("\t","").replace("\r","").replace("\r\n","").replace("\n","");}
    private String  C_city_code;public String  get_C_city_code(){return C_city_code;}public void set_C_city_code(String C_city_code){this.C_city_code=C_city_code==null?"-":C_city_code.replace("\t","").replace("\r","").replace("\r\n","").replace("\n","");}
    private String  C_order_show;public String  get_C_order_show(){return C_order_show;}public void set_C_order_show(String C_order_show){this.C_order_show=C_order_show==null?"-":C_order_show.replace("\t","").replace("\r","").replace("\r\n","").replace("\n","");}
    private String  C_plate_prefix;public String  get_C_plate_prefix(){return C_plate_prefix;}public void set_C_plate_prefix(String C_plate_prefix){this.C_plate_prefix=C_plate_prefix==null?"-":C_plate_prefix.replace("\t","").replace("\r","").replace("\r\n","").replace("\n","");}
    private String  C_lat;public String  get_C_lat(){return C_lat;}public void set_C_lat(String C_lat){this.C_lat=C_lat==null?"-":C_lat.replace("\t","").replace("\r","").replace("\r\n","").replace("\n","");}
    private String  C_city_id;public String  get_C_city_id(){return C_city_id;}public void set_C_city_id(String C_city_id){this.C_city_id=C_city_id==null?"-":C_city_id.replace("\t","").replace("\r","").replace("\r\n","").replace("\n","");}
    private int  C_IsFinish;public int  get_C_IsFinish(){return C_IsFinish;}public void set_C_IsFinish(int C_IsFinish){this.C_IsFinish=C_IsFinish;}
    private String  C_UpdateTime;public String  get_C_UpdateTime(){return C_UpdateTime;}public void set_C_UpdateTime(String C_UpdateTime){this.C_UpdateTime=C_UpdateTime==null?"-":C_UpdateTime.replace("\t","").replace("\r","").replace("\r\n","").replace("\n","");}
}
